#include "gmock/gmock.h"
#include "gtest/gtest.h"
#include "Variable.h"
using namespace testing;
using namespace OperationArchitecture;

namespace UnitTests
{
	TEST(VariableTests, WhenCreating_ThenCorrectTypeChosen)
	{
		ASSERT_EQ(Variable::Create(static_cast<uint8_t>(0)).Type, UINT8);
		ASSERT_EQ(Variable::Create(static_cast<uint16_t>(0)).Type, UINT16);
		ASSERT_EQ(Variable::Create(static_cast<uint32_t>(0)).Type, UINT32);
		ASSERT_EQ(Variable::Create(static_cast<uint64_t>(0)).Type, UINT64);
		ASSERT_EQ(Variable::Create(static_cast<int8_t>(0)).Type, INT8);
		ASSERT_EQ(Variable::Create(static_cast<int16_t>(0)).Type, INT16);
		ASSERT_EQ(Variable::Create(static_cast<int32_t>(0)).Type, INT32);
		ASSERT_EQ(Variable::Create(static_cast<int64_t>(0)).Type, INT64);
		ASSERT_EQ(Variable::Create(static_cast<float>(0)).Type, FLOAT);
		ASSERT_EQ(Variable::Create(static_cast<double>(0)).Type, DOUBLE);

		struct other 
		{
			uint8_t test[VARIABLE_VALUE_SIZE];
		} __attribute__((packed)); 
		other testOther;

		ASSERT_EQ(Variable::Create(testOther).Type, OTHER);

		struct bigother 
		{
			uint8_t test[VARIABLE_VALUE_SIZE+1];
		};
		bigother testBigOther = {};

		ASSERT_EQ(Variable::Create(testBigOther).Type, BIGOTHER);
		ASSERT_EQ(Variable::Create(&testBigOther).Type, POINTER);
	}
	TEST(VariableTests, WhenGettingSize_ThenCorrectSizeReturned)
	{
		ASSERT_EQ(Variable::Create(static_cast<uint8_t>(0)).Size(), sizeof(uint8_t));
		ASSERT_EQ(Variable::Create(static_cast<uint16_t>(0)).Size(), sizeof(uint16_t));
		ASSERT_EQ(Variable::Create(static_cast<uint32_t>(0)).Size(), sizeof(uint32_t));
		ASSERT_EQ(Variable::Create(static_cast<uint64_t>(0)).Size(), sizeof(uint64_t));
		ASSERT_EQ(Variable::Create(static_cast<int8_t>(0)).Size(), sizeof(int8_t));
		ASSERT_EQ(Variable::Create(static_cast<int16_t>(0)).Size(), sizeof(int16_t));
		ASSERT_EQ(Variable::Create(static_cast<int32_t>(0)).Size(), sizeof(int32_t));
		ASSERT_EQ(Variable::Create(static_cast<int64_t>(0)).Size(), sizeof(int64_t));
		ASSERT_EQ(Variable::Create(static_cast<float>(0)).Size(), sizeof(float));
		ASSERT_EQ(Variable::Create(static_cast<double>(0)).Size(), sizeof(double));

		struct other 
		{
			uint8_t test[VARIABLE_VALUE_SIZE];
		} __attribute__((packed)); 
		other testOther;

		ASSERT_EQ(Variable::Create(testOther).Size(), VARIABLE_VALUE_SIZE);

		struct bigother 
		{
			uint8_t test[VARIABLE_VALUE_SIZE+1];
		};
		bigother testBigOther = {};

		ASSERT_EQ(Variable::Create(testBigOther).Size(), sizeof(testBigOther));
		ASSERT_EQ(Variable::Create(&testBigOther).Size(), sizeof(void *));
	}
	TEST(VariableTests, WhenCasting_ThenCorrectValueReturned)
	{
		ASSERT_EQ(Variable::Create(static_cast<uint8_t>(10)).To<uint8_t>(), 10);
		ASSERT_EQ(Variable::Create(static_cast<uint8_t>(10)).To<uint16_t>(), 10);
		ASSERT_EQ(Variable::Create(static_cast<uint8_t>(10)).To<uint32_t>(), 10);
		ASSERT_EQ(Variable::Create(static_cast<uint8_t>(10)).To<uint64_t>(), 10);
		ASSERT_EQ(Variable::Create(static_cast<uint8_t>(10)).To<int8_t>(), 10);
		ASSERT_EQ(Variable::Create(static_cast<uint8_t>(10)).To<int16_t>(), 10);
		ASSERT_EQ(Variable::Create(static_cast<uint8_t>(10)).To<int32_t>(), 10);
		ASSERT_EQ(Variable::Create(static_cast<uint8_t>(10)).To<int64_t>(), 10);
		ASSERT_EQ(Variable::Create(static_cast<uint8_t>(10)).To<float>(), 10);
		ASSERT_EQ(Variable::Create(static_cast<uint8_t>(10)).To<double>(), 10);
		ASSERT_EQ(Variable::Create(static_cast<uint8_t>(10)).To<VariableBase>().Type, UINT8);
		ASSERT_EQ(Variable::Create(static_cast<uint8_t>(10)).To<Variable>().Type, UINT8);
		ASSERT_EQ(Variable::Create(static_cast<uint16_t>(10)).To<uint8_t>(), 10);
		ASSERT_EQ(Variable::Create(static_cast<uint16_t>(10)).To<uint16_t>(), 10);
		ASSERT_EQ(Variable::Create(static_cast<uint16_t>(10)).To<uint32_t>(), 10);
		ASSERT_EQ(Variable::Create(static_cast<uint16_t>(10)).To<uint64_t>(), 10);
		ASSERT_EQ(Variable::Create(static_cast<uint16_t>(10)).To<int8_t>(), 10);
		ASSERT_EQ(Variable::Create(static_cast<uint16_t>(10)).To<int16_t>(), 10);
		ASSERT_EQ(Variable::Create(static_cast<uint16_t>(10)).To<int32_t>(), 10);
		ASSERT_EQ(Variable::Create(static_cast<uint16_t>(10)).To<int64_t>(), 10);
		ASSERT_EQ(Variable::Create(static_cast<uint16_t>(10)).To<float>(), 10);
		ASSERT_EQ(Variable::Create(static_cast<uint16_t>(10)).To<double>(), 10);
		ASSERT_EQ(Variable::Create(static_cast<uint16_t>(10)).To<VariableBase>().Type, UINT16);
		ASSERT_EQ(Variable::Create(static_cast<uint16_t>(10)).To<Variable>().Type, UINT16);
		ASSERT_EQ(Variable::Create(static_cast<uint32_t>(10)).To<uint8_t>(), 10);
		ASSERT_EQ(Variable::Create(static_cast<uint32_t>(10)).To<uint16_t>(), 10);
		ASSERT_EQ(Variable::Create(static_cast<uint32_t>(10)).To<uint32_t>(), 10);
		ASSERT_EQ(Variable::Create(static_cast<uint32_t>(10)).To<uint64_t>(), 10);
		ASSERT_EQ(Variable::Create(static_cast<uint32_t>(10)).To<int8_t>(), 10);
		ASSERT_EQ(Variable::Create(static_cast<uint32_t>(10)).To<int16_t>(), 10);
		ASSERT_EQ(Variable::Create(static_cast<uint32_t>(10)).To<int32_t>(), 10);
		ASSERT_EQ(Variable::Create(static_cast<uint32_t>(10)).To<int64_t>(), 10);
		ASSERT_EQ(Variable::Create(static_cast<uint32_t>(10)).To<float>(), 10);
		ASSERT_EQ(Variable::Create(static_cast<uint32_t>(10)).To<double>(), 10);
		ASSERT_EQ(Variable::Create(static_cast<uint32_t>(10)).To<VariableBase>().Type, UINT32);
		ASSERT_EQ(Variable::Create(static_cast<uint32_t>(10)).To<Variable>().Type, UINT32);
		ASSERT_EQ(Variable::Create(static_cast<uint64_t>(10)).To<uint8_t>(), 10);
		ASSERT_EQ(Variable::Create(static_cast<uint64_t>(10)).To<uint16_t>(), 10);
		ASSERT_EQ(Variable::Create(static_cast<uint64_t>(10)).To<uint32_t>(), 10);
		ASSERT_EQ(Variable::Create(static_cast<uint64_t>(10)).To<uint64_t>(), 10);
		ASSERT_EQ(Variable::Create(static_cast<uint64_t>(10)).To<int8_t>(), 10);
		ASSERT_EQ(Variable::Create(static_cast<uint64_t>(10)).To<int16_t>(), 10);
		ASSERT_EQ(Variable::Create(static_cast<uint64_t>(10)).To<int32_t>(), 10);
		ASSERT_EQ(Variable::Create(static_cast<uint64_t>(10)).To<int64_t>(), 10);
		ASSERT_EQ(Variable::Create(static_cast<uint64_t>(10)).To<float>(), 10);
		ASSERT_EQ(Variable::Create(static_cast<uint64_t>(10)).To<double>(), 10);
		ASSERT_EQ(Variable::Create(static_cast<uint64_t>(10)).To<VariableBase>().Type, UINT64);
		ASSERT_EQ(Variable::Create(static_cast<uint64_t>(10)).To<Variable>().Type, UINT64);
		ASSERT_EQ(Variable::Create(static_cast<int8_t>(10)).To<uint8_t>(), 10);
		ASSERT_EQ(Variable::Create(static_cast<int8_t>(10)).To<uint16_t>(), 10);
		ASSERT_EQ(Variable::Create(static_cast<int8_t>(10)).To<uint32_t>(), 10);
		ASSERT_EQ(Variable::Create(static_cast<int8_t>(10)).To<uint64_t>(), 10);
		ASSERT_EQ(Variable::Create(static_cast<int8_t>(10)).To<int8_t>(), 10);
		ASSERT_EQ(Variable::Create(static_cast<int8_t>(10)).To<int16_t>(), 10);
		ASSERT_EQ(Variable::Create(static_cast<int8_t>(10)).To<int32_t>(), 10);
		ASSERT_EQ(Variable::Create(static_cast<int8_t>(10)).To<int64_t>(), 10);
		ASSERT_EQ(Variable::Create(static_cast<int8_t>(10)).To<float>(), 10);
		ASSERT_EQ(Variable::Create(static_cast<int8_t>(10)).To<double>(), 10);
		ASSERT_EQ(Variable::Create(static_cast<int8_t>(10)).To<VariableBase>().Type, INT8);
		ASSERT_EQ(Variable::Create(static_cast<int8_t>(10)).To<Variable>().Type, INT8);
		ASSERT_EQ(Variable::Create(static_cast<int16_t>(10)).To<uint8_t>(), 10);
		ASSERT_EQ(Variable::Create(static_cast<int16_t>(10)).To<uint16_t>(), 10);
		ASSERT_EQ(Variable::Create(static_cast<int16_t>(10)).To<uint32_t>(), 10);
		ASSERT_EQ(Variable::Create(static_cast<int16_t>(10)).To<uint64_t>(), 10);
		ASSERT_EQ(Variable::Create(static_cast<int16_t>(10)).To<int8_t>(), 10);
		ASSERT_EQ(Variable::Create(static_cast<int16_t>(10)).To<int16_t>(), 10);
		ASSERT_EQ(Variable::Create(static_cast<int16_t>(10)).To<int32_t>(), 10);
		ASSERT_EQ(Variable::Create(static_cast<int16_t>(10)).To<int64_t>(), 10);
		ASSERT_EQ(Variable::Create(static_cast<int16_t>(10)).To<float>(), 10);
		ASSERT_EQ(Variable::Create(static_cast<int16_t>(10)).To<double>(), 10);
		ASSERT_EQ(Variable::Create(static_cast<int16_t>(10)).To<VariableBase>().Type, INT16);
		ASSERT_EQ(Variable::Create(static_cast<int16_t>(10)).To<Variable>().Type, INT16);
		ASSERT_EQ(Variable::Create(static_cast<int32_t>(10)).To<uint8_t>(), 10);
		ASSERT_EQ(Variable::Create(static_cast<int32_t>(10)).To<uint16_t>(), 10);
		ASSERT_EQ(Variable::Create(static_cast<int32_t>(10)).To<uint32_t>(), 10);
		ASSERT_EQ(Variable::Create(static_cast<int32_t>(10)).To<uint64_t>(), 10);
		ASSERT_EQ(Variable::Create(static_cast<int32_t>(10)).To<int8_t>(), 10);
		ASSERT_EQ(Variable::Create(static_cast<int32_t>(10)).To<int16_t>(), 10);
		ASSERT_EQ(Variable::Create(static_cast<int32_t>(10)).To<int32_t>(), 10);
		ASSERT_EQ(Variable::Create(static_cast<int32_t>(10)).To<int64_t>(), 10);
		ASSERT_EQ(Variable::Create(static_cast<int32_t>(10)).To<float>(), 10);
		ASSERT_EQ(Variable::Create(static_cast<int32_t>(10)).To<double>(), 10);
		ASSERT_EQ(Variable::Create(static_cast<int32_t>(10)).To<VariableBase>().Type, INT32);
		ASSERT_EQ(Variable::Create(static_cast<int32_t>(10)).To<Variable>().Type, INT32);
		ASSERT_EQ(Variable::Create(static_cast<int64_t>(10)).To<uint8_t>(), 10);
		ASSERT_EQ(Variable::Create(static_cast<int64_t>(10)).To<uint16_t>(), 10);
		ASSERT_EQ(Variable::Create(static_cast<int64_t>(10)).To<uint32_t>(), 10);
		ASSERT_EQ(Variable::Create(static_cast<int64_t>(10)).To<uint64_t>(), 10);
		ASSERT_EQ(Variable::Create(static_cast<int64_t>(10)).To<int8_t>(), 10);
		ASSERT_EQ(Variable::Create(static_cast<int64_t>(10)).To<int16_t>(), 10);
		ASSERT_EQ(Variable::Create(static_cast<int64_t>(10)).To<int32_t>(), 10);
		ASSERT_EQ(Variable::Create(static_cast<int64_t>(10)).To<int64_t>(), 10);
		ASSERT_EQ(Variable::Create(static_cast<int64_t>(10)).To<float>(), 10);
		ASSERT_EQ(Variable::Create(static_cast<int64_t>(10)).To<double>(), 10);
		ASSERT_EQ(Variable::Create(static_cast<int64_t>(10)).To<VariableBase>().Type, INT64);
		ASSERT_EQ(Variable::Create(static_cast<int64_t>(10)).To<Variable>().Type, INT64);
		ASSERT_EQ(Variable::Create(static_cast<float>(10)).To<uint8_t>(), 10);
		ASSERT_EQ(Variable::Create(static_cast<float>(10)).To<uint16_t>(), 10);
		ASSERT_EQ(Variable::Create(static_cast<float>(10)).To<uint32_t>(), 10);
		ASSERT_EQ(Variable::Create(static_cast<float>(10)).To<uint64_t>(), 10);
		ASSERT_EQ(Variable::Create(static_cast<float>(10)).To<int8_t>(), 10);
		ASSERT_EQ(Variable::Create(static_cast<float>(10)).To<int16_t>(), 10);
		ASSERT_EQ(Variable::Create(static_cast<float>(10)).To<int32_t>(), 10);
		ASSERT_EQ(Variable::Create(static_cast<float>(10)).To<int64_t>(), 10);
		ASSERT_EQ(Variable::Create(static_cast<float>(10)).To<float>(), 10);
		ASSERT_EQ(Variable::Create(static_cast<float>(10)).To<double>(), 10);
		ASSERT_EQ(Variable::Create(static_cast<float>(10)).To<VariableBase>().Type, FLOAT);
		ASSERT_EQ(Variable::Create(static_cast<float>(10)).To<Variable>().Type, FLOAT);
		ASSERT_EQ(Variable::Create(static_cast<double>(10)).To<uint8_t>(), 10);
		ASSERT_EQ(Variable::Create(static_cast<double>(10)).To<uint16_t>(), 10);
		ASSERT_EQ(Variable::Create(static_cast<double>(10)).To<uint32_t>(), 10);
		ASSERT_EQ(Variable::Create(static_cast<double>(10)).To<uint64_t>(), 10);
		ASSERT_EQ(Variable::Create(static_cast<double>(10)).To<int8_t>(), 10);
		ASSERT_EQ(Variable::Create(static_cast<double>(10)).To<int16_t>(), 10);
		ASSERT_EQ(Variable::Create(static_cast<double>(10)).To<int32_t>(), 10);
		ASSERT_EQ(Variable::Create(static_cast<double>(10)).To<int64_t>(), 10);
		ASSERT_EQ(Variable::Create(static_cast<double>(10)).To<float>(), 10);
		ASSERT_EQ(Variable::Create(static_cast<double>(10)).To<double>(), 10);
		ASSERT_EQ(Variable::Create(static_cast<double>(10)).To<VariableBase>().Type, DOUBLE);
		ASSERT_EQ(Variable::Create(static_cast<double>(10)).To<Variable>().Type, DOUBLE);

		struct other 
		{
			uint8_t test[VARIABLE_VALUE_SIZE];
		} __attribute__((packed)); 
		other testOther;
		testOther.test[VARIABLE_VALUE_SIZE-1] = 25;

		ASSERT_EQ(Variable::Create(testOther).To<other>().test[VARIABLE_VALUE_SIZE-1], 25);

		struct bigother 
		{
			uint8_t test[VARIABLE_VALUE_SIZE+1];
		};
		bigother testBigOther;
		testBigOther.test[VARIABLE_VALUE_SIZE] = 28;

		ASSERT_EQ(Variable::Create(testBigOther).To<bigother>().test[VARIABLE_VALUE_SIZE], 28);
		ASSERT_EQ(Variable::Create(testBigOther).To<bigother*>()->test[VARIABLE_VALUE_SIZE], 28);
		ASSERT_EQ(Variable::Create(&testBigOther).To<bigother>().test[VARIABLE_VALUE_SIZE], 28);
		ASSERT_EQ(Variable::Create(&testBigOther).To<bigother*>()->test[VARIABLE_VALUE_SIZE], 28);
	}

	TEST(VariableTests, WhenAdding_ThenCorrectValueReturned)
	{
		Variable result;
		
		result = Variable::Create(static_cast<uint8_t>(10)) + Variable::Create(static_cast<uint8_t>(10));
		ASSERT_EQ(result.Type, UINT8);
		ASSERT_EQ(result.To<uint8_t>(), 20);
		result = Variable::Create(static_cast<uint8_t>(10)) + Variable::Create(static_cast<uint16_t>(10));
		ASSERT_EQ(result.Type, UINT8);
		ASSERT_EQ(result.To<uint8_t>(), 20);
		result = Variable::Create(static_cast<uint8_t>(10)) + Variable::Create(static_cast<uint32_t>(10));
		ASSERT_EQ(result.Type, UINT8);
		ASSERT_EQ(result.To<uint8_t>(), 20);
		result = Variable::Create(static_cast<uint8_t>(10)) + Variable::Create(static_cast<uint64_t>(10));
		ASSERT_EQ(result.Type, UINT8);
		ASSERT_EQ(result.To<uint8_t>(), 20);
		result = Variable::Create(static_cast<uint8_t>(10)) + Variable::Create(static_cast<int8_t>(10));
		ASSERT_EQ(result.Type, UINT8);
		ASSERT_EQ(result.To<uint8_t>(), 20);
		result = Variable::Create(static_cast<uint8_t>(10)) + Variable::Create(static_cast<int16_t>(10));
		ASSERT_EQ(result.Type, UINT8);
		ASSERT_EQ(result.To<uint8_t>(), 20);
		result = Variable::Create(static_cast<uint8_t>(10)) + Variable::Create(static_cast<int32_t>(10));
		ASSERT_EQ(result.Type, UINT8);
		ASSERT_EQ(result.To<uint8_t>(), 20);
		result = Variable::Create(static_cast<uint8_t>(10)) + Variable::Create(static_cast<int64_t>(10));
		ASSERT_EQ(result.Type, UINT8);
		ASSERT_EQ(result.To<int8_t>(), 20);
		result = Variable::Create(static_cast<uint8_t>(10)) + Variable::Create(static_cast<int8_t>(-20));
		ASSERT_EQ(result.Type, INT8);
		ASSERT_EQ(result.To<int8_t>(), -10);
		result = Variable::Create(static_cast<uint8_t>(10)) + Variable::Create(static_cast<int16_t>(-20));
		ASSERT_EQ(result.Type, INT8);
		ASSERT_EQ(result.To<int8_t>(), -10);
		result = Variable::Create(static_cast<uint8_t>(10)) + Variable::Create(static_cast<int32_t>(-20));
		ASSERT_EQ(result.Type, INT8);
		ASSERT_EQ(result.To<int8_t>(), -10);
		result = Variable::Create(static_cast<uint8_t>(10)) + Variable::Create(static_cast<int64_t>(-20));
		ASSERT_EQ(result.Type, INT8);
		ASSERT_EQ(result.To<int8_t>(), -10);
		result = Variable::Create(static_cast<uint8_t>(10)) + Variable::Create(static_cast<int64_t>(-139));
		ASSERT_EQ(result.Type, INT16);
		ASSERT_EQ(result.To<int16_t>(), -129);
		result = Variable::Create(static_cast<uint8_t>(10)) + Variable::Create(static_cast<int64_t>(-32779));
		ASSERT_EQ(result.Type, INT32);
		ASSERT_EQ(result.To<int32_t>(), -32769);
		result = Variable::Create(static_cast<uint8_t>(10)) + Variable::Create(-static_cast<int64_t>(2147483659));
		ASSERT_EQ(result.Type, INT64);
		ASSERT_EQ(result.To<int64_t>(), -static_cast<int64_t>(2147483649));
		result = Variable::Create(static_cast<uint8_t>(10)) + Variable::Create(static_cast<uint8_t>(250));
		ASSERT_EQ(result.Type, UINT16);
		ASSERT_EQ(result.To<uint16_t>(), 260);
		result = Variable::Create(static_cast<uint8_t>(10)) + Variable::Create(static_cast<uint16_t>(65534));
		ASSERT_EQ(result.Type, UINT32);
		ASSERT_EQ(result.To<uint32_t>(), 65544);
		result = Variable::Create(static_cast<uint8_t>(10)) + Variable::Create(static_cast<uint32_t>(4294967294));
		ASSERT_EQ(result.Type, UINT64);
		ASSERT_EQ(result.To<uint64_t>(), 4294967304);
		result = Variable::Create(static_cast<uint8_t>(10)) + Variable::Create(static_cast<float>(10));
		ASSERT_EQ(result.Type, FLOAT);
		ASSERT_EQ(result.To<float>(), 20);
		result = Variable::Create(static_cast<uint8_t>(10)) + Variable::Create(static_cast<double>(10));
		ASSERT_EQ(result.Type, DOUBLE);
		ASSERT_EQ(result.To<double>(), 20);
		
		result = Variable::Create(static_cast<uint16_t>(10)) + Variable::Create(static_cast<uint8_t>(10));
		ASSERT_EQ(result.Type, UINT16);
		ASSERT_EQ(result.To<uint16_t>(), 20);
		result = Variable::Create(static_cast<uint16_t>(10)) + Variable::Create(static_cast<uint16_t>(10));
		ASSERT_EQ(result.Type, UINT16);
		ASSERT_EQ(result.To<uint16_t>(), 20);
		result = Variable::Create(static_cast<uint16_t>(10)) + Variable::Create(static_cast<uint32_t>(10));
		ASSERT_EQ(result.Type, UINT16);
		ASSERT_EQ(result.To<uint16_t>(), 20);
		result = Variable::Create(static_cast<uint16_t>(10)) + Variable::Create(static_cast<uint64_t>(10));
		ASSERT_EQ(result.Type, UINT16);
		ASSERT_EQ(result.To<uint16_t>(), 20);
		result = Variable::Create(static_cast<uint16_t>(10)) + Variable::Create(static_cast<int8_t>(10));
		ASSERT_EQ(result.Type, UINT16);
		ASSERT_EQ(result.To<uint16_t>(), 20);
		result = Variable::Create(static_cast<uint16_t>(10)) + Variable::Create(static_cast<int16_t>(10));
		ASSERT_EQ(result.Type, UINT16);
		ASSERT_EQ(result.To<uint16_t>(), 20);
		result = Variable::Create(static_cast<uint16_t>(10)) + Variable::Create(static_cast<int32_t>(10));
		ASSERT_EQ(result.Type, UINT16);
		ASSERT_EQ(result.To<uint16_t>(), 20);
		result = Variable::Create(static_cast<uint16_t>(10)) + Variable::Create(static_cast<int64_t>(10));
		ASSERT_EQ(result.Type, UINT16);
		ASSERT_EQ(result.To<uint16_t>(), 20);
		result = Variable::Create(static_cast<uint16_t>(10)) + Variable::Create(static_cast<int8_t>(-20));
		ASSERT_EQ(result.Type, INT16);
		ASSERT_EQ(result.To<int16_t>(), -10);
		result = Variable::Create(static_cast<uint16_t>(10)) + Variable::Create(static_cast<int16_t>(-20));
		ASSERT_EQ(result.Type, INT16);
		ASSERT_EQ(result.To<int16_t>(), -10);
		result = Variable::Create(static_cast<uint16_t>(10)) + Variable::Create(static_cast<int32_t>(-20));
		ASSERT_EQ(result.Type, INT16);
		ASSERT_EQ(result.To<int16_t>(), -10);
		result = Variable::Create(static_cast<uint16_t>(10)) + Variable::Create(static_cast<int64_t>(-20));
		ASSERT_EQ(result.Type, INT16);
		ASSERT_EQ(result.To<int16_t>(), -10);
		result = Variable::Create(static_cast<uint16_t>(10)) + Variable::Create(static_cast<int64_t>(-139));
		ASSERT_EQ(result.Type, INT16);
		ASSERT_EQ(result.To<int16_t>(), -129);
		result = Variable::Create(static_cast<uint16_t>(10)) + Variable::Create(static_cast<int64_t>(-32779));
		ASSERT_EQ(result.Type, INT32);
		ASSERT_EQ(result.To<int32_t>(), -32769);
		result = Variable::Create(static_cast<uint16_t>(10)) + Variable::Create(-static_cast<int64_t>(2147483659));
		ASSERT_EQ(result.Type, INT64);
		ASSERT_EQ(result.To<int64_t>(), -static_cast<int64_t>(2147483649));
		result = Variable::Create(static_cast<uint16_t>(10)) + Variable::Create(static_cast<uint8_t>(250));
		ASSERT_EQ(result.Type, UINT16);
		ASSERT_EQ(result.To<uint16_t>(), 260);
		result = Variable::Create(static_cast<uint16_t>(10)) + Variable::Create(static_cast<uint16_t>(65534));
		ASSERT_EQ(result.Type, UINT32);
		ASSERT_EQ(result.To<uint32_t>(), 65544);
		result = Variable::Create(static_cast<uint16_t>(10)) + Variable::Create(static_cast<uint32_t>(4294967294));
		ASSERT_EQ(result.Type, UINT64);
		ASSERT_EQ(result.To<uint64_t>(), 4294967304);
		result = Variable::Create(static_cast<uint16_t>(10)) + Variable::Create(static_cast<float>(10));
		ASSERT_EQ(result.Type, FLOAT);
		ASSERT_EQ(result.To<float>(), 20);
		result = Variable::Create(static_cast<uint16_t>(10)) + Variable::Create(static_cast<double>(10));
		ASSERT_EQ(result.Type, DOUBLE);
		ASSERT_EQ(result.To<double>(), 20);
		
		result = Variable::Create(static_cast<uint32_t>(10)) + Variable::Create(static_cast<uint8_t>(10));
		ASSERT_EQ(result.Type, UINT32);
		ASSERT_EQ(result.To<uint32_t>(), 20);
		result = Variable::Create(static_cast<uint32_t>(10)) + Variable::Create(static_cast<uint16_t>(10));
		ASSERT_EQ(result.Type, UINT32);
		ASSERT_EQ(result.To<uint32_t>(), 20);
		result = Variable::Create(static_cast<uint32_t>(10)) + Variable::Create(static_cast<uint32_t>(10));
		ASSERT_EQ(result.Type, UINT32);
		ASSERT_EQ(result.To<uint32_t>(), 20);
		result = Variable::Create(static_cast<uint32_t>(10)) + Variable::Create(static_cast<uint64_t>(10));
		ASSERT_EQ(result.Type, UINT32);
		ASSERT_EQ(result.To<uint32_t>(), 20);
		result = Variable::Create(static_cast<uint32_t>(10)) + Variable::Create(static_cast<int8_t>(10));
		ASSERT_EQ(result.Type, UINT32);
		ASSERT_EQ(result.To<uint32_t>(), 20);
		result = Variable::Create(static_cast<uint32_t>(10)) + Variable::Create(static_cast<int16_t>(10));
		ASSERT_EQ(result.Type, UINT32);
		ASSERT_EQ(result.To<uint32_t>(), 20);
		result = Variable::Create(static_cast<uint32_t>(10)) + Variable::Create(static_cast<int32_t>(10));
		ASSERT_EQ(result.Type, UINT32);
		ASSERT_EQ(result.To<uint32_t>(), 20);
		result = Variable::Create(static_cast<uint32_t>(10)) + Variable::Create(static_cast<int64_t>(10));
		ASSERT_EQ(result.Type, UINT32);
		ASSERT_EQ(result.To<uint32_t>(), 20);
		result = Variable::Create(static_cast<uint32_t>(10)) + Variable::Create(static_cast<int8_t>(-20));
		ASSERT_EQ(result.Type, INT32);
		ASSERT_EQ(result.To<int32_t>(), -10);
		result = Variable::Create(static_cast<uint32_t>(10)) + Variable::Create(static_cast<int16_t>(-20));
		ASSERT_EQ(result.Type, INT32);
		ASSERT_EQ(result.To<int32_t>(), -10);
		result = Variable::Create(static_cast<uint32_t>(10)) + Variable::Create(static_cast<int32_t>(-20));
		ASSERT_EQ(result.Type, INT32);
		ASSERT_EQ(result.To<int32_t>(), -10);
		result = Variable::Create(static_cast<uint32_t>(10)) + Variable::Create(static_cast<int64_t>(-20));
		ASSERT_EQ(result.Type, INT32);
		ASSERT_EQ(result.To<int32_t>(), -10);
		result = Variable::Create(static_cast<uint32_t>(10)) + Variable::Create(static_cast<int64_t>(-139));
		ASSERT_EQ(result.Type, INT32);
		ASSERT_EQ(result.To<int32_t>(), -129);
		result = Variable::Create(static_cast<uint32_t>(10)) + Variable::Create(static_cast<int64_t>(-32779));
		ASSERT_EQ(result.Type, INT32);
		ASSERT_EQ(result.To<int32_t>(), -32769);
		result = Variable::Create(static_cast<uint32_t>(10)) + Variable::Create(-static_cast<int64_t>(2147483659));
		ASSERT_EQ(result.Type, INT64);
		ASSERT_EQ(result.To<int64_t>(), -static_cast<int64_t>(2147483649));
		result = Variable::Create(static_cast<uint32_t>(10)) + Variable::Create(static_cast<uint8_t>(250));
		ASSERT_EQ(result.Type, UINT32);
		ASSERT_EQ(result.To<uint32_t>(), 260);
		result = Variable::Create(static_cast<uint32_t>(10)) + Variable::Create(static_cast<uint16_t>(65534));
		ASSERT_EQ(result.Type, UINT32);
		ASSERT_EQ(result.To<uint32_t>(), 65544);
		result = Variable::Create(static_cast<uint32_t>(10)) + Variable::Create(static_cast<uint32_t>(4294967294));
		ASSERT_EQ(result.Type, UINT64);
		ASSERT_EQ(result.To<uint64_t>(), 4294967304);
		result = Variable::Create(static_cast<uint32_t>(10)) + Variable::Create(static_cast<float>(10));
		ASSERT_EQ(result.Type, FLOAT);
		ASSERT_EQ(result.To<float>(), 20);
		result = Variable::Create(static_cast<uint32_t>(10)) + Variable::Create(static_cast<double>(10));
		ASSERT_EQ(result.Type, DOUBLE);
		ASSERT_EQ(result.To<double>(), 20);
		
		result = Variable::Create(static_cast<uint64_t>(10)) + Variable::Create(static_cast<uint8_t>(10));
		ASSERT_EQ(result.Type, UINT64);
		ASSERT_EQ(result.To<uint64_t>(), 20);
		result = Variable::Create(static_cast<uint64_t>(10)) + Variable::Create(static_cast<uint16_t>(10));
		ASSERT_EQ(result.Type, UINT64);
		ASSERT_EQ(result.To<uint64_t>(), 20);
		result = Variable::Create(static_cast<uint64_t>(10)) + Variable::Create(static_cast<uint32_t>(10));
		ASSERT_EQ(result.Type, UINT64);
		ASSERT_EQ(result.To<uint64_t>(), 20);
		result = Variable::Create(static_cast<uint64_t>(10)) + Variable::Create(static_cast<uint64_t>(10));
		ASSERT_EQ(result.Type, UINT64);
		ASSERT_EQ(result.To<uint64_t>(), 20);
		result = Variable::Create(static_cast<uint64_t>(10)) + Variable::Create(static_cast<int8_t>(10));
		ASSERT_EQ(result.Type, UINT64);
		ASSERT_EQ(result.To<uint64_t>(), 20);
		result = Variable::Create(static_cast<uint64_t>(10)) + Variable::Create(static_cast<int16_t>(10));
		ASSERT_EQ(result.Type, UINT64);
		ASSERT_EQ(result.To<uint64_t>(), 20);
		result = Variable::Create(static_cast<uint64_t>(10)) + Variable::Create(static_cast<int32_t>(10));
		ASSERT_EQ(result.Type, UINT64);
		ASSERT_EQ(result.To<uint64_t>(), 20);
		result = Variable::Create(static_cast<uint64_t>(10)) + Variable::Create(static_cast<int64_t>(10));
		ASSERT_EQ(result.Type, UINT64);
		ASSERT_EQ(result.To<uint64_t>(), 20);
		result = Variable::Create(static_cast<uint64_t>(10)) + Variable::Create(static_cast<int8_t>(-20));
		ASSERT_EQ(result.Type, INT64);
		ASSERT_EQ(result.To<int64_t>(), -10);
		result = Variable::Create(static_cast<uint64_t>(10)) + Variable::Create(static_cast<int16_t>(-20));
		ASSERT_EQ(result.Type, INT64);
		ASSERT_EQ(result.To<int64_t>(), -10);
		result = Variable::Create(static_cast<uint64_t>(10)) + Variable::Create(static_cast<int32_t>(-20));
		ASSERT_EQ(result.Type, INT64);
		ASSERT_EQ(result.To<int64_t>(), -10);
		result = Variable::Create(static_cast<uint64_t>(10)) + Variable::Create(static_cast<int64_t>(-20));
		ASSERT_EQ(result.Type, INT64);
		ASSERT_EQ(result.To<int64_t>(), -10);
		result = Variable::Create(static_cast<uint64_t>(10)) + Variable::Create(static_cast<int64_t>(-139));
		ASSERT_EQ(result.Type, INT64);
		ASSERT_EQ(result.To<int64_t>(), -129);
		result = Variable::Create(static_cast<uint64_t>(10)) + Variable::Create(static_cast<int64_t>(-32779));
		ASSERT_EQ(result.Type, INT64);
		ASSERT_EQ(result.To<int64_t>(), -32769);
		result = Variable::Create(static_cast<uint64_t>(10)) + Variable::Create(-static_cast<int64_t>(2147483659));
		ASSERT_EQ(result.Type, INT64);
		ASSERT_EQ(result.To<int64_t>(), -static_cast<int64_t>(2147483649));
		result = Variable::Create(static_cast<uint64_t>(10)) + Variable::Create(static_cast<uint8_t>(250));
		ASSERT_EQ(result.Type, UINT64);
		ASSERT_EQ(result.To<uint64_t>(), 260);
		result = Variable::Create(static_cast<uint64_t>(10)) + Variable::Create(static_cast<uint16_t>(65534));
		ASSERT_EQ(result.Type, UINT64);
		ASSERT_EQ(result.To<uint64_t>(), 65544);
		result = Variable::Create(static_cast<uint64_t>(10)) + Variable::Create(static_cast<uint32_t>(4294967294));
		ASSERT_EQ(result.Type, UINT64);
		ASSERT_EQ(result.To<uint64_t>(), 4294967304);
		result = Variable::Create(static_cast<uint64_t>(10)) + Variable::Create(static_cast<float>(10));
		ASSERT_EQ(result.Type, FLOAT);
		ASSERT_EQ(result.To<float>(), 20);
		result = Variable::Create(static_cast<uint64_t>(10)) + Variable::Create(static_cast<double>(10));
		ASSERT_EQ(result.Type, DOUBLE);
		ASSERT_EQ(result.To<double>(), 20);
		
		result = Variable::Create(static_cast<int8_t>(10)) + Variable::Create(static_cast<uint8_t>(10));
		ASSERT_EQ(result.Type, INT8);
		ASSERT_EQ(result.To<int8_t>(), 20);
		result = Variable::Create(static_cast<int8_t>(10)) + Variable::Create(static_cast<uint16_t>(10));
		ASSERT_EQ(result.Type, INT8);
		ASSERT_EQ(result.To<int8_t>(), 20);
		result = Variable::Create(static_cast<int8_t>(10)) + Variable::Create(static_cast<uint32_t>(10));
		ASSERT_EQ(result.Type, INT8);
		ASSERT_EQ(result.To<int8_t>(), 20);
		result = Variable::Create(static_cast<int8_t>(10)) + Variable::Create(static_cast<uint64_t>(10));
		ASSERT_EQ(result.Type, INT8);
		ASSERT_EQ(result.To<int8_t>(), 20);
		result = Variable::Create(static_cast<int8_t>(10)) + Variable::Create(static_cast<int8_t>(10));
		ASSERT_EQ(result.Type, INT8);
		ASSERT_EQ(result.To<int8_t>(), 20);
		result = Variable::Create(static_cast<int8_t>(10)) + Variable::Create(static_cast<int16_t>(10));
		ASSERT_EQ(result.Type, INT8);
		ASSERT_EQ(result.To<int8_t>(), 20);
		result = Variable::Create(static_cast<int8_t>(10)) + Variable::Create(static_cast<int32_t>(10));
		ASSERT_EQ(result.Type, INT8);
		ASSERT_EQ(result.To<int8_t>(), 20);
		result = Variable::Create(static_cast<int8_t>(10)) + Variable::Create(static_cast<int64_t>(10));
		ASSERT_EQ(result.Type, INT8);
		ASSERT_EQ(result.To<int8_t>(), 20);
		result = Variable::Create(static_cast<int8_t>(10)) + Variable::Create(static_cast<int8_t>(-20));
		ASSERT_EQ(result.Type, INT8);
		ASSERT_EQ(result.To<int8_t>(), -10);
		result = Variable::Create(static_cast<int8_t>(10)) + Variable::Create(static_cast<int16_t>(-20));
		ASSERT_EQ(result.Type, INT8);
		ASSERT_EQ(result.To<int8_t>(), -10);
		result = Variable::Create(static_cast<int8_t>(10)) + Variable::Create(static_cast<int32_t>(-20));
		ASSERT_EQ(result.Type, INT8);
		ASSERT_EQ(result.To<int8_t>(), -10);
		result = Variable::Create(static_cast<int8_t>(10)) + Variable::Create(static_cast<int64_t>(-20));
		ASSERT_EQ(result.Type, INT8);
		ASSERT_EQ(result.To<int8_t>(), -10);
		result = Variable::Create(static_cast<int8_t>(10)) + Variable::Create(static_cast<int64_t>(-139));
		ASSERT_EQ(result.Type, INT16);
		ASSERT_EQ(result.To<int16_t>(), -129);
		result = Variable::Create(static_cast<int8_t>(10)) + Variable::Create(static_cast<int64_t>(-32779));
		ASSERT_EQ(result.Type, INT32);
		ASSERT_EQ(result.To<int32_t>(), -32769);
		result = Variable::Create(static_cast<int8_t>(10)) + Variable::Create(-static_cast<int64_t>(2147483659));
		ASSERT_EQ(result.Type, INT64);
		ASSERT_EQ(result.To<int64_t>(), -static_cast<int64_t>(2147483649));
		result = Variable::Create(static_cast<int8_t>(10)) + Variable::Create(static_cast<uint8_t>(128));
		ASSERT_EQ(result.Type, INT16);
		ASSERT_EQ(result.To<int16_t>(), 138);
		result = Variable::Create(static_cast<int8_t>(10)) + Variable::Create(static_cast<uint16_t>(32768));
		ASSERT_EQ(result.Type, INT32);
		ASSERT_EQ(result.To<int32_t>(), 32778);
		result = Variable::Create(static_cast<int8_t>(10)) + Variable::Create(static_cast<uint32_t>(2147483648));
		ASSERT_EQ(result.Type, INT64);
		ASSERT_EQ(result.To<int64_t>(), 2147483658);
		result = Variable::Create(static_cast<int8_t>(10)) + Variable::Create(static_cast<float>(10));
		ASSERT_EQ(result.Type, FLOAT);
		ASSERT_EQ(result.To<float>(), 20);
		result = Variable::Create(static_cast<int8_t>(10)) + Variable::Create(static_cast<double>(10));
		ASSERT_EQ(result.Type, DOUBLE);
		ASSERT_EQ(result.To<double>(), 20);
		
		result = Variable::Create(static_cast<int16_t>(10)) + Variable::Create(static_cast<uint8_t>(10));
		ASSERT_EQ(result.Type, INT16);
		ASSERT_EQ(result.To<int16_t>(), 20);
		result = Variable::Create(static_cast<int16_t>(10)) + Variable::Create(static_cast<uint16_t>(10));
		ASSERT_EQ(result.Type, INT16);
		ASSERT_EQ(result.To<int16_t>(), 20);
		result = Variable::Create(static_cast<int16_t>(10)) + Variable::Create(static_cast<uint32_t>(10));
		ASSERT_EQ(result.Type, INT16);
		ASSERT_EQ(result.To<int16_t>(), 20);
		result = Variable::Create(static_cast<int16_t>(10)) + Variable::Create(static_cast<uint64_t>(10));
		ASSERT_EQ(result.Type, INT16);
		ASSERT_EQ(result.To<int16_t>(), 20);
		result = Variable::Create(static_cast<int16_t>(10)) + Variable::Create(static_cast<int8_t>(10));
		ASSERT_EQ(result.Type, INT16);
		ASSERT_EQ(result.To<int16_t>(), 20);
		result = Variable::Create(static_cast<int16_t>(10)) + Variable::Create(static_cast<int16_t>(10));
		ASSERT_EQ(result.Type, INT16);
		ASSERT_EQ(result.To<int16_t>(), 20);
		result = Variable::Create(static_cast<int16_t>(10)) + Variable::Create(static_cast<int32_t>(10));
		ASSERT_EQ(result.Type, INT16);
		ASSERT_EQ(result.To<int16_t>(), 20);
		result = Variable::Create(static_cast<int16_t>(10)) + Variable::Create(static_cast<int64_t>(10));
		ASSERT_EQ(result.Type, INT16);
		ASSERT_EQ(result.To<int16_t>(), 20);
		result = Variable::Create(static_cast<int16_t>(10)) + Variable::Create(static_cast<int8_t>(-20));
		ASSERT_EQ(result.Type, INT16);
		ASSERT_EQ(result.To<int16_t>(), -10);
		result = Variable::Create(static_cast<int16_t>(10)) + Variable::Create(static_cast<int16_t>(-20));
		ASSERT_EQ(result.Type, INT16);
		ASSERT_EQ(result.To<int16_t>(), -10);
		result = Variable::Create(static_cast<int16_t>(10)) + Variable::Create(static_cast<int32_t>(-20));
		ASSERT_EQ(result.Type, INT16);
		ASSERT_EQ(result.To<int16_t>(), -10);
		result = Variable::Create(static_cast<int16_t>(10)) + Variable::Create(static_cast<int64_t>(-20));
		ASSERT_EQ(result.Type, INT16);
		ASSERT_EQ(result.To<int16_t>(), -10);
		result = Variable::Create(static_cast<int16_t>(10)) + Variable::Create(static_cast<int64_t>(-139));
		ASSERT_EQ(result.Type, INT16);
		ASSERT_EQ(result.To<int16_t>(), -129);
		result = Variable::Create(static_cast<int16_t>(10)) + Variable::Create(static_cast<int64_t>(-32779));
		ASSERT_EQ(result.Type, INT32);
		ASSERT_EQ(result.To<int32_t>(), -32769);
		result = Variable::Create(static_cast<int16_t>(10)) + Variable::Create(-static_cast<int64_t>(2147483659));
		ASSERT_EQ(result.Type, INT64);
		ASSERT_EQ(result.To<int64_t>(), -static_cast<int64_t>(2147483649));
		result = Variable::Create(static_cast<int16_t>(10)) + Variable::Create(static_cast<uint8_t>(128));
		ASSERT_EQ(result.Type, INT16);
		ASSERT_EQ(result.To<int16_t>(), 138);
		result = Variable::Create(static_cast<int16_t>(10)) + Variable::Create(static_cast<uint16_t>(32768));
		ASSERT_EQ(result.Type, INT32);
		ASSERT_EQ(result.To<int32_t>(), 32778);
		result = Variable::Create(static_cast<int16_t>(10)) + Variable::Create(static_cast<uint32_t>(2147483648));
		ASSERT_EQ(result.Type, INT64);
		ASSERT_EQ(result.To<int64_t>(), 2147483658);
		result = Variable::Create(static_cast<int16_t>(10)) + Variable::Create(static_cast<float>(10));
		ASSERT_EQ(result.Type, FLOAT);
		ASSERT_EQ(result.To<float>(), 20);
		result = Variable::Create(static_cast<int16_t>(10)) + Variable::Create(static_cast<double>(10));
		ASSERT_EQ(result.Type, DOUBLE);
		ASSERT_EQ(result.To<double>(), 20);
		
		result = Variable::Create(static_cast<int32_t>(10)) + Variable::Create(static_cast<uint8_t>(10));
		ASSERT_EQ(result.Type, INT32);
		ASSERT_EQ(result.To<int32_t>(), 20);
		result = Variable::Create(static_cast<int32_t>(10)) + Variable::Create(static_cast<uint16_t>(10));
		ASSERT_EQ(result.Type, INT32);
		ASSERT_EQ(result.To<int32_t>(), 20);
		result = Variable::Create(static_cast<int32_t>(10)) + Variable::Create(static_cast<uint32_t>(10));
		ASSERT_EQ(result.Type, INT32);
		ASSERT_EQ(result.To<int32_t>(), 20);
		result = Variable::Create(static_cast<int32_t>(10)) + Variable::Create(static_cast<uint64_t>(10));
		ASSERT_EQ(result.Type, INT32);
		ASSERT_EQ(result.To<int32_t>(), 20);
		result = Variable::Create(static_cast<int32_t>(10)) + Variable::Create(static_cast<int8_t>(10));
		ASSERT_EQ(result.Type, INT32);
		ASSERT_EQ(result.To<int32_t>(), 20);
		result = Variable::Create(static_cast<int32_t>(10)) + Variable::Create(static_cast<int16_t>(10));
		ASSERT_EQ(result.Type, INT32);
		ASSERT_EQ(result.To<int32_t>(), 20);
		result = Variable::Create(static_cast<int32_t>(10)) + Variable::Create(static_cast<int32_t>(10));
		ASSERT_EQ(result.Type, INT32);
		ASSERT_EQ(result.To<int32_t>(), 20);
		result = Variable::Create(static_cast<int32_t>(10)) + Variable::Create(static_cast<int64_t>(10));
		ASSERT_EQ(result.Type, INT32);
		ASSERT_EQ(result.To<int32_t>(), 20);
		result = Variable::Create(static_cast<int32_t>(10)) + Variable::Create(static_cast<int8_t>(-20));
		ASSERT_EQ(result.Type, INT32);
		ASSERT_EQ(result.To<int32_t>(), -10);
		result = Variable::Create(static_cast<int32_t>(10)) + Variable::Create(static_cast<int16_t>(-20));
		ASSERT_EQ(result.Type, INT32);
		ASSERT_EQ(result.To<int32_t>(), -10);
		result = Variable::Create(static_cast<int32_t>(10)) + Variable::Create(static_cast<int32_t>(-20));
		ASSERT_EQ(result.Type, INT32);
		ASSERT_EQ(result.To<int32_t>(), -10);
		result = Variable::Create(static_cast<int32_t>(10)) + Variable::Create(static_cast<int64_t>(-20));
		ASSERT_EQ(result.Type, INT32);
		ASSERT_EQ(result.To<int32_t>(), -10);
		result = Variable::Create(static_cast<int32_t>(10)) + Variable::Create(static_cast<int64_t>(-139));
		ASSERT_EQ(result.Type, INT32);
		ASSERT_EQ(result.To<int32_t>(), -129);
		result = Variable::Create(static_cast<int32_t>(10)) + Variable::Create(static_cast<int64_t>(-32779));
		ASSERT_EQ(result.Type, INT32);
		ASSERT_EQ(result.To<int32_t>(), -32769);
		result = Variable::Create(static_cast<int32_t>(10)) + Variable::Create(-static_cast<int64_t>(2147483659));
		ASSERT_EQ(result.Type, INT64);
		ASSERT_EQ(result.To<int64_t>(), -static_cast<int64_t>(2147483649));
		result = Variable::Create(static_cast<int32_t>(10)) + Variable::Create(static_cast<uint8_t>(128));
		ASSERT_EQ(result.Type, INT32);
		ASSERT_EQ(result.To<int32_t>(), 138);
		result = Variable::Create(static_cast<int32_t>(10)) + Variable::Create(static_cast<uint16_t>(32768));
		ASSERT_EQ(result.Type, INT32);
		ASSERT_EQ(result.To<int32_t>(), 32778);
		result = Variable::Create(static_cast<int32_t>(10)) + Variable::Create(static_cast<uint32_t>(2147483648));
		ASSERT_EQ(result.Type, INT64);
		ASSERT_EQ(result.To<int64_t>(), 2147483658);
		result = Variable::Create(static_cast<int32_t>(10)) + Variable::Create(static_cast<float>(10));
		ASSERT_EQ(result.Type, FLOAT);
		ASSERT_EQ(result.To<float>(), 20);
		result = Variable::Create(static_cast<int32_t>(10)) + Variable::Create(static_cast<double>(10));
		ASSERT_EQ(result.Type, DOUBLE);
		ASSERT_EQ(result.To<double>(), 20);
		
		result = Variable::Create(static_cast<int64_t>(10)) + Variable::Create(static_cast<uint8_t>(10));
		ASSERT_EQ(result.Type, INT64);
		ASSERT_EQ(result.To<int64_t>(), 20);
		result = Variable::Create(static_cast<int64_t>(10)) + Variable::Create(static_cast<uint16_t>(10));
		ASSERT_EQ(result.Type, INT64);
		ASSERT_EQ(result.To<int64_t>(), 20);
		result = Variable::Create(static_cast<int64_t>(10)) + Variable::Create(static_cast<uint32_t>(10));
		ASSERT_EQ(result.Type, INT64);
		ASSERT_EQ(result.To<int64_t>(), 20);
		result = Variable::Create(static_cast<int64_t>(10)) + Variable::Create(static_cast<uint64_t>(10));
		ASSERT_EQ(result.Type, INT64);
		ASSERT_EQ(result.To<int64_t>(), 20);
		result = Variable::Create(static_cast<int64_t>(10)) + Variable::Create(static_cast<int8_t>(10));
		ASSERT_EQ(result.Type, INT64);
		ASSERT_EQ(result.To<int64_t>(), 20);
		result = Variable::Create(static_cast<int64_t>(10)) + Variable::Create(static_cast<int16_t>(10));
		ASSERT_EQ(result.Type, INT64);
		ASSERT_EQ(result.To<int64_t>(), 20);
		result = Variable::Create(static_cast<int64_t>(10)) + Variable::Create(static_cast<int32_t>(10));
		ASSERT_EQ(result.Type, INT64);
		ASSERT_EQ(result.To<int64_t>(), 20);
		result = Variable::Create(static_cast<int64_t>(10)) + Variable::Create(static_cast<int64_t>(10));
		ASSERT_EQ(result.Type, INT64);
		ASSERT_EQ(result.To<int64_t>(), 20);
		result = Variable::Create(static_cast<int64_t>(10)) + Variable::Create(static_cast<int8_t>(-20));
		ASSERT_EQ(result.Type, INT64);
		ASSERT_EQ(result.To<int64_t>(), -10);
		result = Variable::Create(static_cast<int64_t>(10)) + Variable::Create(static_cast<int16_t>(-20));
		ASSERT_EQ(result.Type, INT64);
		ASSERT_EQ(result.To<int64_t>(), -10);
		result = Variable::Create(static_cast<int64_t>(10)) + Variable::Create(static_cast<int32_t>(-20));
		ASSERT_EQ(result.Type, INT64);
		ASSERT_EQ(result.To<int64_t>(), -10);
		result = Variable::Create(static_cast<int64_t>(10)) + Variable::Create(static_cast<int64_t>(-20));
		ASSERT_EQ(result.Type, INT64);
		ASSERT_EQ(result.To<int64_t>(), -10);
		result = Variable::Create(static_cast<int64_t>(10)) + Variable::Create(static_cast<int64_t>(-139));
		ASSERT_EQ(result.Type, INT64);
		ASSERT_EQ(result.To<int64_t>(), -129);
		result = Variable::Create(static_cast<int64_t>(10)) + Variable::Create(static_cast<int64_t>(-32779));
		ASSERT_EQ(result.Type, INT64);
		ASSERT_EQ(result.To<int64_t>(), -32769);
		result = Variable::Create(static_cast<int64_t>(10)) + Variable::Create(-static_cast<int64_t>(2147483659));
		ASSERT_EQ(result.Type, INT64);
		ASSERT_EQ(result.To<int64_t>(), -static_cast<int64_t>(2147483649));
		result = Variable::Create(static_cast<int64_t>(10)) + Variable::Create(static_cast<uint8_t>(128));
		ASSERT_EQ(result.Type, INT64);
		ASSERT_EQ(result.To<int64_t>(), 138);
		result = Variable::Create(static_cast<int64_t>(10)) + Variable::Create(static_cast<uint16_t>(32768));
		ASSERT_EQ(result.Type, INT64);
		ASSERT_EQ(result.To<int64_t>(), 32778);
		result = Variable::Create(static_cast<int64_t>(10)) + Variable::Create(static_cast<uint32_t>(2147483648));
		ASSERT_EQ(result.Type, INT64);
		ASSERT_EQ(result.To<int64_t>(), 2147483658);
		result = Variable::Create(static_cast<int64_t>(10)) + Variable::Create(static_cast<float>(10));
		ASSERT_EQ(result.Type, FLOAT);
		ASSERT_EQ(result.To<float>(), 20);
		result = Variable::Create(static_cast<int64_t>(10)) + Variable::Create(static_cast<double>(10));
		ASSERT_EQ(result.Type, DOUBLE);
		ASSERT_EQ(result.To<double>(), 20);
		
		result = Variable::Create(static_cast<float>(10)) + Variable::Create(static_cast<uint8_t>(10));
		ASSERT_EQ(result.Type, FLOAT);
		ASSERT_EQ(result.To<float>(), 20);
		result = Variable::Create(static_cast<float>(10)) + Variable::Create(static_cast<uint16_t>(10));
		ASSERT_EQ(result.Type, FLOAT);
		ASSERT_EQ(result.To<float>(), 20);
		result = Variable::Create(static_cast<float>(10)) + Variable::Create(static_cast<uint32_t>(10));
		ASSERT_EQ(result.Type, FLOAT);
		ASSERT_EQ(result.To<float>(), 20);
		result = Variable::Create(static_cast<float>(10)) + Variable::Create(static_cast<uint64_t>(10));
		ASSERT_EQ(result.Type, FLOAT);
		ASSERT_EQ(result.To<float>(), 20);
		result = Variable::Create(static_cast<float>(10)) + Variable::Create(static_cast<int8_t>(10));
		ASSERT_EQ(result.Type, FLOAT);
		ASSERT_EQ(result.To<float>(), 20);
		result = Variable::Create(static_cast<float>(10)) + Variable::Create(static_cast<int16_t>(10));
		ASSERT_EQ(result.Type, FLOAT);
		ASSERT_EQ(result.To<float>(), 20);
		result = Variable::Create(static_cast<float>(10)) + Variable::Create(static_cast<int32_t>(10));
		ASSERT_EQ(result.Type, FLOAT);
		ASSERT_EQ(result.To<float>(), 20);
		result = Variable::Create(static_cast<float>(10)) + Variable::Create(static_cast<int64_t>(10));
		ASSERT_EQ(result.Type, FLOAT);
		ASSERT_EQ(result.To<float>(), 20);
		result = Variable::Create(static_cast<float>(10)) + Variable::Create(static_cast<float>(10));
		ASSERT_EQ(result.Type, FLOAT);
		ASSERT_EQ(result.To<float>(), 20);
		result = Variable::Create(static_cast<float>(10)) + Variable::Create(static_cast<double>(10));
		ASSERT_EQ(result.Type, DOUBLE);
		ASSERT_EQ(result.To<double>(), 20);
		
		result = Variable::Create(static_cast<double>(10)) + Variable::Create(static_cast<uint8_t>(10));
		ASSERT_EQ(result.Type, DOUBLE);
		ASSERT_EQ(result.To<double>(), 20);
		result = Variable::Create(static_cast<double>(10)) + Variable::Create(static_cast<uint16_t>(10));
		ASSERT_EQ(result.Type, DOUBLE);
		ASSERT_EQ(result.To<double>(), 20);
		result = Variable::Create(static_cast<double>(10)) + Variable::Create(static_cast<uint32_t>(10));
		ASSERT_EQ(result.Type, DOUBLE);
		ASSERT_EQ(result.To<double>(), 20);
		result = Variable::Create(static_cast<double>(10)) + Variable::Create(static_cast<uint64_t>(10));
		ASSERT_EQ(result.Type, DOUBLE);
		ASSERT_EQ(result.To<double>(), 20);
		result = Variable::Create(static_cast<double>(10)) + Variable::Create(static_cast<int8_t>(10));
		ASSERT_EQ(result.Type, DOUBLE);
		ASSERT_EQ(result.To<double>(), 20);
		result = Variable::Create(static_cast<double>(10)) + Variable::Create(static_cast<int16_t>(10));
		ASSERT_EQ(result.Type, DOUBLE);
		ASSERT_EQ(result.To<double>(), 20);
		result = Variable::Create(static_cast<double>(10)) + Variable::Create(static_cast<int32_t>(10));
		ASSERT_EQ(result.Type, DOUBLE);
		ASSERT_EQ(result.To<double>(), 20);
		result = Variable::Create(static_cast<double>(10)) + Variable::Create(static_cast<int64_t>(10));
		ASSERT_EQ(result.Type, DOUBLE);
		ASSERT_EQ(result.To<double>(), 20);
		result = Variable::Create(static_cast<double>(10)) + Variable::Create(static_cast<float>(10));
		ASSERT_EQ(result.Type, DOUBLE);
		ASSERT_EQ(result.To<double>(), 20);
		result = Variable::Create(static_cast<float>(10)) + Variable::Create(static_cast<double>(10));
		ASSERT_EQ(result.Type, DOUBLE);
		ASSERT_EQ(result.To<double>(), 20);
	}

	TEST(VariableTests, WhenSubtacting_ThenCorrectValueReturned)
	{
		Variable result;
		
		result = Variable::Create(static_cast<uint8_t>(10)) - Variable::Create(static_cast<uint8_t>(5));
		ASSERT_EQ(result.Type, UINT8);
		ASSERT_EQ(result.To<uint8_t>(), 5);

		result = Variable::Create(static_cast<uint8_t>(10)) - Variable::Create(static_cast<uint8_t>(15));
		ASSERT_EQ(result.Type, INT8);
		ASSERT_EQ(result.To<int8_t>(), -5);
	}

	TEST(VariableTests, WhenMultiplying_ThenCorrectValueReturned)
	{
		Variable result;
		
		result = Variable::Create(static_cast<uint8_t>(10)) * Variable::Create(static_cast<uint8_t>(5));
		ASSERT_EQ(result.Type, UINT8);
		ASSERT_EQ(result.To<uint8_t>(), 50);

		result = Variable::Create(static_cast<uint8_t>(10)) * Variable::Create(static_cast<int8_t>(-15));
		ASSERT_EQ(result.Type, INT16);
		ASSERT_EQ(result.To<int16_t>(), -150);
	}

	TEST(VariableTests, WhenDividing_ThenCorrectValueReturned)
	{
		Variable result;
		
		result = Variable::Create(static_cast<uint8_t>(10)) / Variable::Create(static_cast<uint8_t>(5));
		ASSERT_EQ(result.Type, UINT8);
		ASSERT_EQ(result.To<uint8_t>(), 2);

		result = Variable::Create(static_cast<uint16_t>(150)) / Variable::Create(static_cast<int8_t>(-15));
		ASSERT_EQ(result.Type, INT16);
		ASSERT_EQ(result.To<int16_t>(), -10);
	}
}
