#include "gmock/gmock.h"
#include "gtest/gtest.h"
#include "Variable.h"
using namespace testing;
using namespace OperationArchitecture;

namespace UnitTests
{
	TEST(VariableTests, WhenCreating_ThenCorrectTypeChosen)
	{
		ASSERT_EQ(Variable(static_cast<uint8_t>(0)).Type, UINT8);
		ASSERT_EQ(Variable(static_cast<uint16_t>(0)).Type, UINT16);
		ASSERT_EQ(Variable(static_cast<uint32_t>(0)).Type, UINT32);
		ASSERT_EQ(Variable(static_cast<uint64_t>(0)).Type, UINT64);
		ASSERT_EQ(Variable(static_cast<int8_t>(0)).Type, INT8);
		ASSERT_EQ(Variable(static_cast<int16_t>(0)).Type, INT16);
		ASSERT_EQ(Variable(static_cast<int32_t>(0)).Type, INT32);
		ASSERT_EQ(Variable(static_cast<int64_t>(0)).Type, INT64);
		ASSERT_EQ(Variable(static_cast<float>(0)).Type, FLOAT);
		ASSERT_EQ(Variable(static_cast<double>(0)).Type, DOUBLE);

		struct other 
		{
			uint8_t test[VARIABLE_VALUE_SIZE-1];
		} __attribute__((packed)); 
		other testOther;

		ASSERT_EQ(Variable(testOther).Type, OTHER);

		struct bigother 
		{
			uint8_t test[VARIABLE_VALUE_SIZE];
		};
		bigother testBigOther = {};

		ASSERT_EQ(Variable(testBigOther).Type, BIGOTHER);
		ASSERT_EQ(Variable(&testBigOther).Type, POINTER);
	}
	TEST(VariableTests, WhenGettingSize_ThenCorrectSizeReturned)
	{
		ASSERT_EQ(Variable(static_cast<uint8_t>(0)).Size(), sizeof(uint8_t));
		ASSERT_EQ(Variable(static_cast<uint16_t>(0)).Size(), sizeof(uint16_t));
		ASSERT_EQ(Variable(static_cast<uint32_t>(0)).Size(), sizeof(uint32_t));
		ASSERT_EQ(Variable(static_cast<uint64_t>(0)).Size(), sizeof(uint64_t));
		ASSERT_EQ(Variable(static_cast<int8_t>(0)).Size(), sizeof(int8_t));
		ASSERT_EQ(Variable(static_cast<int16_t>(0)).Size(), sizeof(int16_t));
		ASSERT_EQ(Variable(static_cast<int32_t>(0)).Size(), sizeof(int32_t));
		ASSERT_EQ(Variable(static_cast<int64_t>(0)).Size(), sizeof(int64_t));
		ASSERT_EQ(Variable(static_cast<float>(0)).Size(), sizeof(float));
		ASSERT_EQ(Variable(static_cast<double>(0)).Size(), sizeof(double));

		struct other 
		{
			uint8_t test[VARIABLE_VALUE_SIZE-5];
		} __attribute__((packed)); 
		other testOther;

		ASSERT_EQ(Variable(testOther).Size(), VARIABLE_VALUE_SIZE-5);

		struct bigother 
		{
			uint8_t test[VARIABLE_VALUE_SIZE+1];
		};
		bigother testBigOther = {};

		ASSERT_EQ(Variable(testBigOther).Size(), sizeof(testBigOther));
		ASSERT_EQ(Variable(&testBigOther).Size(), sizeof(testBigOther));
	}
	TEST(VariableTests, WhenCasting_ThenCorrectValueReturned)
	{
		ASSERT_EQ(							 Variable(static_cast<uint8_t>(10)).Type, 	UINT8	);
		ASSERT_EQ(static_cast<VariableBase>	(Variable(static_cast<uint8_t>(10))).Type, 	UINT8	);
		ASSERT_EQ(static_cast<uint8_t	>	(Variable(static_cast<uint8_t>(10))), 		10		);
		ASSERT_EQ(static_cast<uint16_t	>	(Variable(static_cast<uint8_t>(10))), 		10		);
		ASSERT_EQ(static_cast<uint32_t	>	(Variable(static_cast<uint8_t>(10))), 		10		);
		ASSERT_EQ(static_cast<uint64_t	>	(Variable(static_cast<uint8_t>(10))), 		10		);
		ASSERT_EQ(static_cast<uint8_t	>	(Variable(static_cast<uint8_t>(10))), 		10		);
		ASSERT_EQ(static_cast<uint16_t	>	(Variable(static_cast<uint8_t>(10))), 		10		);
		ASSERT_EQ(static_cast<uint32_t	>	(Variable(static_cast<uint8_t>(10))), 		10		);
		ASSERT_EQ(static_cast<uint64_t	>	(Variable(static_cast<uint8_t>(10))), 		10		);
		ASSERT_EQ(static_cast<float		>	(Variable(static_cast<uint8_t>(10))), 		10		);
		ASSERT_EQ(static_cast<double	>	(Variable(static_cast<uint8_t>(10))), 		10		);
		ASSERT_EQ(							 Variable(static_cast<uint16_t>(10)).Type, 	UINT16	);
		ASSERT_EQ(static_cast<VariableBase>	(Variable(static_cast<uint16_t>(10))).Type,	UINT16	);
		ASSERT_EQ(static_cast<uint8_t	>	(Variable(static_cast<uint16_t>(10))), 		10		);
		ASSERT_EQ(static_cast<uint16_t	>	(Variable(static_cast<uint16_t>(10))), 		10		);
		ASSERT_EQ(static_cast<uint32_t	>	(Variable(static_cast<uint16_t>(10))), 		10		);
		ASSERT_EQ(static_cast<uint64_t	>	(Variable(static_cast<uint16_t>(10))), 		10		);
		ASSERT_EQ(static_cast<uint8_t	>	(Variable(static_cast<uint16_t>(10))), 		10		);
		ASSERT_EQ(static_cast<uint16_t	>	(Variable(static_cast<uint16_t>(10))), 		10		);
		ASSERT_EQ(static_cast<uint32_t	>	(Variable(static_cast<uint16_t>(10))), 		10		);
		ASSERT_EQ(static_cast<uint64_t	>	(Variable(static_cast<uint16_t>(10))), 		10		);
		ASSERT_EQ(static_cast<float		>	(Variable(static_cast<uint16_t>(10))), 		10		);
		ASSERT_EQ(static_cast<double	>	(Variable(static_cast<uint16_t>(10))), 		10		);
		ASSERT_EQ(							 Variable(static_cast<uint32_t>(10)).Type, 	UINT32	);
		ASSERT_EQ(static_cast<VariableBase>	(Variable(static_cast<uint32_t>(10))).Type, UINT32	);
		ASSERT_EQ(static_cast<uint8_t	>	(Variable(static_cast<uint32_t>(10))), 		10		);
		ASSERT_EQ(static_cast<uint16_t	>	(Variable(static_cast<uint32_t>(10))), 		10		);
		ASSERT_EQ(static_cast<uint32_t	>	(Variable(static_cast<uint32_t>(10))), 		10		);
		ASSERT_EQ(static_cast<uint64_t	>	(Variable(static_cast<uint32_t>(10))), 		10		);
		ASSERT_EQ(static_cast<uint8_t	>	(Variable(static_cast<uint32_t>(10))), 		10		);
		ASSERT_EQ(static_cast<uint16_t	>	(Variable(static_cast<uint32_t>(10))), 		10		);
		ASSERT_EQ(static_cast<uint32_t	>	(Variable(static_cast<uint32_t>(10))), 		10		);
		ASSERT_EQ(static_cast<uint64_t	>	(Variable(static_cast<uint32_t>(10))), 		10		);
		ASSERT_EQ(static_cast<float		>	(Variable(static_cast<uint32_t>(10))), 		10		);
		ASSERT_EQ(static_cast<double	>	(Variable(static_cast<uint32_t>(10))), 		10		);
		ASSERT_EQ(							 Variable(static_cast<uint64_t>(10)).Type, 	UINT64	);
		ASSERT_EQ(static_cast<VariableBase>	(Variable(static_cast<uint64_t>(10))).Type, UINT64	);
		ASSERT_EQ(static_cast<uint8_t	>	(Variable(static_cast<uint64_t>(10))), 		10		);
		ASSERT_EQ(static_cast<uint16_t	>	(Variable(static_cast<uint64_t>(10))), 		10		);
		ASSERT_EQ(static_cast<uint32_t	>	(Variable(static_cast<uint64_t>(10))), 		10		);
		ASSERT_EQ(static_cast<uint64_t	>	(Variable(static_cast<uint64_t>(10))), 		10		);
		ASSERT_EQ(static_cast<uint8_t	>	(Variable(static_cast<uint64_t>(10))), 		10		);
		ASSERT_EQ(static_cast<uint16_t	>	(Variable(static_cast<uint64_t>(10))), 		10		);
		ASSERT_EQ(static_cast<uint32_t	>	(Variable(static_cast<uint64_t>(10))), 		10		);
		ASSERT_EQ(static_cast<uint64_t	>	(Variable(static_cast<uint64_t>(10))), 		10		);
		ASSERT_EQ(static_cast<float		>	(Variable(static_cast<uint64_t>(10))), 		10		);
		ASSERT_EQ(static_cast<double	>	(Variable(static_cast<uint64_t>(10))), 		10		);
		ASSERT_EQ(							 Variable(static_cast<int8_t>(10)).Type, 	INT8	);
		ASSERT_EQ(static_cast<VariableBase>	(Variable(static_cast<int8_t>(10))).Type, 	INT8	);
		ASSERT_EQ(static_cast<uint8_t	>	(Variable(static_cast<int8_t>(10))), 		10		);
		ASSERT_EQ(static_cast<uint16_t	>	(Variable(static_cast<int8_t>(10))), 		10		);
		ASSERT_EQ(static_cast<uint32_t	>	(Variable(static_cast<int8_t>(10))), 		10		);
		ASSERT_EQ(static_cast<uint64_t	>	(Variable(static_cast<int8_t>(10))), 		10		);
		ASSERT_EQ(static_cast<uint8_t	>	(Variable(static_cast<int8_t>(10))), 		10		);
		ASSERT_EQ(static_cast<uint16_t	>	(Variable(static_cast<int8_t>(10))), 		10		);
		ASSERT_EQ(static_cast<uint32_t	>	(Variable(static_cast<int8_t>(10))), 		10		);
		ASSERT_EQ(static_cast<uint64_t	>	(Variable(static_cast<int8_t>(10))), 		10		);
		ASSERT_EQ(static_cast<float		>	(Variable(static_cast<int8_t>(10))), 		10		);
		ASSERT_EQ(static_cast<double	>	(Variable(static_cast<int8_t>(10))), 		10		);
		ASSERT_EQ(							 Variable(static_cast<int16_t>(10)).Type, 	INT16	);
		ASSERT_EQ(static_cast<VariableBase>	(Variable(static_cast<int16_t>(10))).Type,	INT16	);
		ASSERT_EQ(static_cast<uint8_t	>	(Variable(static_cast<int16_t>(10))), 		10		);
		ASSERT_EQ(static_cast<uint16_t	>	(Variable(static_cast<int16_t>(10))), 		10		);
		ASSERT_EQ(static_cast<uint32_t	>	(Variable(static_cast<int16_t>(10))), 		10		);
		ASSERT_EQ(static_cast<uint64_t	>	(Variable(static_cast<int16_t>(10))), 		10		);
		ASSERT_EQ(static_cast<uint8_t	>	(Variable(static_cast<int16_t>(10))), 		10		);
		ASSERT_EQ(static_cast<uint16_t	>	(Variable(static_cast<int16_t>(10))), 		10		);
		ASSERT_EQ(static_cast<uint32_t	>	(Variable(static_cast<int16_t>(10))), 		10		);
		ASSERT_EQ(static_cast<uint64_t	>	(Variable(static_cast<int16_t>(10))), 		10		);
		ASSERT_EQ(static_cast<float		>	(Variable(static_cast<int16_t>(10))), 		10		);
		ASSERT_EQ(static_cast<double	>	(Variable(static_cast<int16_t>(10))), 		10		);
		ASSERT_EQ(							 Variable(static_cast<int32_t>(10)).Type, 	INT32	);
		ASSERT_EQ(static_cast<VariableBase>	(Variable(static_cast<int32_t>(10))).Type,  INT32	);
		ASSERT_EQ(static_cast<uint8_t	>	(Variable(static_cast<int32_t>(10))), 		10		);
		ASSERT_EQ(static_cast<uint16_t	>	(Variable(static_cast<int32_t>(10))), 		10		);
		ASSERT_EQ(static_cast<uint32_t	>	(Variable(static_cast<int32_t>(10))), 		10		);
		ASSERT_EQ(static_cast<uint64_t	>	(Variable(static_cast<int32_t>(10))), 		10		);
		ASSERT_EQ(static_cast<uint8_t	>	(Variable(static_cast<int32_t>(10))), 		10		);
		ASSERT_EQ(static_cast<uint16_t	>	(Variable(static_cast<int32_t>(10))), 		10		);
		ASSERT_EQ(static_cast<uint32_t	>	(Variable(static_cast<int32_t>(10))), 		10		);
		ASSERT_EQ(static_cast<uint64_t	>	(Variable(static_cast<int32_t>(10))), 		10		);
		ASSERT_EQ(static_cast<float		>	(Variable(static_cast<int32_t>(10))), 		10		);
		ASSERT_EQ(static_cast<double	>	(Variable(static_cast<int32_t>(10))), 		10		);
		ASSERT_EQ(							 Variable(static_cast<int64_t>(10)).Type, 	INT64	);
		ASSERT_EQ(static_cast<VariableBase>	(Variable(static_cast<int64_t>(10))).Type,  INT64	);
		ASSERT_EQ(static_cast<uint8_t	>	(Variable(static_cast<int64_t>(10))), 		10		);
		ASSERT_EQ(static_cast<uint16_t	>	(Variable(static_cast<int64_t>(10))), 		10		);
		ASSERT_EQ(static_cast<uint32_t	>	(Variable(static_cast<int64_t>(10))), 		10		);
		ASSERT_EQ(static_cast<uint64_t	>	(Variable(static_cast<int64_t>(10))), 		10		);
		ASSERT_EQ(static_cast<uint8_t	>	(Variable(static_cast<int64_t>(10))), 		10		);
		ASSERT_EQ(static_cast<uint16_t	>	(Variable(static_cast<int64_t>(10))), 		10		);
		ASSERT_EQ(static_cast<uint32_t	>	(Variable(static_cast<int64_t>(10))), 		10		);
		ASSERT_EQ(static_cast<uint64_t	>	(Variable(static_cast<int64_t>(10))), 		10		);
		ASSERT_EQ(static_cast<float		>	(Variable(static_cast<int64_t>(10))), 		10		);
		ASSERT_EQ(static_cast<double	>	(Variable(static_cast<int64_t>(10))), 		10		);
		ASSERT_EQ(							 Variable(static_cast<float>(10.5f)).Type, 	FLOAT	);
		ASSERT_EQ(static_cast<VariableBase>	(Variable(static_cast<float>(10.5f))).Type, FLOAT	);
		ASSERT_EQ(static_cast<uint8_t	>	(Variable(static_cast<float>(10.5f))), 		10		);
		ASSERT_EQ(static_cast<uint16_t	>	(Variable(static_cast<float>(10.5f))), 		10		);
		ASSERT_EQ(static_cast<uint32_t	>	(Variable(static_cast<float>(10.5f))), 		10		);
		ASSERT_EQ(static_cast<uint64_t	>	(Variable(static_cast<float>(10.5f))), 		10		);
		ASSERT_EQ(static_cast<uint8_t	>	(Variable(static_cast<float>(10.5f))), 		10		);
		ASSERT_EQ(static_cast<uint16_t	>	(Variable(static_cast<float>(10.5f))), 		10		);
		ASSERT_EQ(static_cast<uint32_t	>	(Variable(static_cast<float>(10.5f))), 		10		);
		ASSERT_EQ(static_cast<uint64_t	>	(Variable(static_cast<float>(10.5f))), 		10		);
		ASSERT_EQ(static_cast<float		>	(Variable(static_cast<float>(10.5f))), 		10.5f	);
		ASSERT_EQ(static_cast<double	>	(Variable(static_cast<float>(10.5f))), 		10.5	);
		ASSERT_EQ(							 Variable(static_cast<double>(10.5)).Type, 	DOUBLE	);
		ASSERT_EQ(static_cast<VariableBase>	(Variable(static_cast<double>(10.5))).Type, DOUBLE	);
		ASSERT_EQ(static_cast<uint8_t	>	(Variable(static_cast<double>(10.5))), 		10		);
		ASSERT_EQ(static_cast<uint16_t	>	(Variable(static_cast<double>(10.5))), 		10		);
		ASSERT_EQ(static_cast<uint32_t	>	(Variable(static_cast<double>(10.5))), 		10		);
		ASSERT_EQ(static_cast<uint64_t	>	(Variable(static_cast<double>(10.5))), 		10		);
		ASSERT_EQ(static_cast<uint8_t	>	(Variable(static_cast<double>(10.5))), 		10		);
		ASSERT_EQ(static_cast<uint16_t	>	(Variable(static_cast<double>(10.5))), 		10		);
		ASSERT_EQ(static_cast<uint32_t	>	(Variable(static_cast<double>(10.5))), 		10		);
		ASSERT_EQ(static_cast<uint64_t	>	(Variable(static_cast<double>(10.5))), 		10		);
		ASSERT_EQ(static_cast<float		>	(Variable(static_cast<double>(10.5))), 		10.5f	);
		ASSERT_EQ(static_cast<double	>	(Variable(static_cast<double>(10.5))), 		10.5		);

		struct other 
		{
			uint8_t test[VARIABLE_VALUE_SIZE-1];
		} __attribute__((packed)); 
		other testOther;
		testOther.test[VARIABLE_VALUE_SIZE-2] = 25;

		ASSERT_EQ(static_cast<other> (Variable(testOther)).test[VARIABLE_VALUE_SIZE-2], 25);
		ASSERT_EQ(static_cast<other*>(Variable(testOther))->test[VARIABLE_VALUE_SIZE-2], 25);

		struct bigother 
		{
			uint8_t test[VARIABLE_VALUE_SIZE];
		};
		bigother testBigOther;
		testBigOther.test[VARIABLE_VALUE_SIZE-1] = 28;

		ASSERT_EQ(static_cast<bigother> (Variable(testBigOther)).  test[VARIABLE_VALUE_SIZE-1], 28);
		ASSERT_EQ(static_cast<bigother*>(Variable(testBigOther))-> test[VARIABLE_VALUE_SIZE-1], 28);
		ASSERT_EQ(static_cast<bigother> (Variable(&testBigOther)). test[VARIABLE_VALUE_SIZE-1], 28);
		ASSERT_EQ(static_cast<bigother*>(Variable(&testBigOther))->test[VARIABLE_VALUE_SIZE-1], 28);
	}

	TEST(VariableTests, WhenAdding_ThenCorrectValueReturned)
	{
		Variable result;
		
		result = Variable(static_cast<uint8_t>(10)) + Variable(static_cast<uint8_t>(10));
		ASSERT_EQ(result.Type, UINT8);
		ASSERT_EQ(result, 20);
		result = Variable(static_cast<uint8_t>(10)) + Variable(static_cast<uint16_t>(10));
		ASSERT_EQ(result.Type, UINT8);
		ASSERT_EQ(result, 20);
		result = Variable(static_cast<uint8_t>(10)) + Variable(static_cast<uint32_t>(10));
		ASSERT_EQ(result.Type, UINT8);
		ASSERT_EQ(result, 20);
		result = Variable(static_cast<uint8_t>(10)) + Variable(static_cast<uint64_t>(10));
		ASSERT_EQ(result.Type, UINT8);
		ASSERT_EQ(result, 20);
		result = Variable(static_cast<uint8_t>(10)) + Variable(static_cast<int8_t>(10));
		ASSERT_EQ(result.Type, UINT8);
		ASSERT_EQ(result, 20);
		result = Variable(static_cast<uint8_t>(10)) + Variable(static_cast<int16_t>(10));
		ASSERT_EQ(result.Type, UINT8);
		ASSERT_EQ(result, 20);
		result = Variable(static_cast<uint8_t>(10)) + Variable(static_cast<int32_t>(10));
		ASSERT_EQ(result.Type, UINT8);
		ASSERT_EQ(result, 20);
		result = Variable(static_cast<uint8_t>(10)) + Variable(static_cast<int64_t>(10));
		ASSERT_EQ(result.Type, UINT8);
		ASSERT_EQ(result, 20);
		result = Variable(static_cast<uint8_t>(10)) + Variable(static_cast<int8_t>(-20));
		ASSERT_EQ(result.Type, INT8);
		ASSERT_EQ(result, -10);
		result = Variable(static_cast<uint8_t>(10)) + Variable(static_cast<int16_t>(-20));
		ASSERT_EQ(result.Type, INT8);
		ASSERT_EQ(result, -10);
		result = Variable(static_cast<uint8_t>(10)) + Variable(static_cast<int32_t>(-20));
		ASSERT_EQ(result.Type, INT8);
		ASSERT_EQ(result, -10);
		result = Variable(static_cast<uint8_t>(10)) + Variable(static_cast<int64_t>(-20));
		ASSERT_EQ(result.Type, INT8);
		ASSERT_EQ(result, -10);
		result = Variable(static_cast<uint8_t>(10)) + Variable(static_cast<int64_t>(-139));
		ASSERT_EQ(result.Type, INT16);
		ASSERT_EQ(result, -129);
		result = Variable(static_cast<uint8_t>(10)) + Variable(static_cast<int64_t>(-32779));
		ASSERT_EQ(result.Type, INT32);
		ASSERT_EQ(result, -32769);
		result = Variable(static_cast<uint8_t>(10)) + Variable(-static_cast<int64_t>(2147483659));
		ASSERT_EQ(result.Type, INT64);
		ASSERT_EQ(result, -static_cast<int64_t>(2147483649));
		result = Variable(static_cast<uint8_t>(10)) + Variable(static_cast<uint8_t>(250));
		ASSERT_EQ(result.Type, UINT16);
		ASSERT_EQ(result, 260);
		result = Variable(static_cast<uint8_t>(10)) + Variable(static_cast<uint16_t>(65534));
		ASSERT_EQ(result.Type, UINT32);
		ASSERT_EQ(result, 65544);
		result = Variable(static_cast<uint8_t>(10)) + Variable(static_cast<uint32_t>(4294967294));
		ASSERT_EQ(result.Type, UINT64);
		ASSERT_EQ(result, 4294967304);
		result = Variable(static_cast<uint8_t>(10)) + Variable(static_cast<float>(10));
		ASSERT_EQ(result.Type, FLOAT);
		ASSERT_EQ(result, 20);
		result = Variable(static_cast<uint8_t>(10)) + Variable(static_cast<double>(10));
		ASSERT_EQ(result.Type, DOUBLE);
		ASSERT_EQ(result, 20);
		
		result = Variable(static_cast<uint16_t>(10)) + Variable(static_cast<uint8_t>(10));
		ASSERT_EQ(result.Type, UINT16);
		ASSERT_EQ(result, 20);
		result = Variable(static_cast<uint16_t>(10)) + Variable(static_cast<uint16_t>(10));
		ASSERT_EQ(result.Type, UINT16);
		ASSERT_EQ(result, 20);
		result = Variable(static_cast<uint16_t>(10)) + Variable(static_cast<uint32_t>(10));
		ASSERT_EQ(result.Type, UINT16);
		ASSERT_EQ(result, 20);
		result = Variable(static_cast<uint16_t>(10)) + Variable(static_cast<uint64_t>(10));
		ASSERT_EQ(result.Type, UINT16);
		ASSERT_EQ(result, 20);
		result = Variable(static_cast<uint16_t>(10)) + Variable(static_cast<int8_t>(10));
		ASSERT_EQ(result.Type, UINT16);
		ASSERT_EQ(result, 20);
		result = Variable(static_cast<uint16_t>(10)) + Variable(static_cast<int16_t>(10));
		ASSERT_EQ(result.Type, UINT16);
		ASSERT_EQ(result, 20);
		result = Variable(static_cast<uint16_t>(10)) + Variable(static_cast<int32_t>(10));
		ASSERT_EQ(result.Type, UINT16);
		ASSERT_EQ(result, 20);
		result = Variable(static_cast<uint16_t>(10)) + Variable(static_cast<int64_t>(10));
		ASSERT_EQ(result.Type, UINT16);
		ASSERT_EQ(result, 20);
		result = Variable(static_cast<uint16_t>(10)) + Variable(static_cast<int8_t>(-20));
		ASSERT_EQ(result.Type, INT16);
		ASSERT_EQ(result, -10);
		result = Variable(static_cast<uint16_t>(10)) + Variable(static_cast<int16_t>(-20));
		ASSERT_EQ(result.Type, INT16);
		ASSERT_EQ(result, -10);
		result = Variable(static_cast<uint16_t>(10)) + Variable(static_cast<int32_t>(-20));
		ASSERT_EQ(result.Type, INT16);
		ASSERT_EQ(result, -10);
		result = Variable(static_cast<uint16_t>(10)) + Variable(static_cast<int64_t>(-20));
		ASSERT_EQ(result.Type, INT16);
		ASSERT_EQ(result, -10);
		result = Variable(static_cast<uint16_t>(10)) + Variable(static_cast<int64_t>(-139));
		ASSERT_EQ(result.Type, INT16);
		ASSERT_EQ(result, -129);
		result = Variable(static_cast<uint16_t>(10)) + Variable(static_cast<int64_t>(-32779));
		ASSERT_EQ(result.Type, INT32);
		ASSERT_EQ(result, -32769);
		result = Variable(static_cast<uint16_t>(10)) + Variable(-static_cast<int64_t>(2147483659));
		ASSERT_EQ(result.Type, INT64);
		ASSERT_EQ(result, -static_cast<int64_t>(2147483649));
		result = Variable(static_cast<uint16_t>(10)) + Variable(static_cast<uint8_t>(250));
		ASSERT_EQ(result.Type, UINT16);
		ASSERT_EQ(result, 260);
		result = Variable(static_cast<uint16_t>(10)) + Variable(static_cast<uint16_t>(65534));
		ASSERT_EQ(result.Type, UINT32);
		ASSERT_EQ(result, 65544);
		result = Variable(static_cast<uint16_t>(10)) + Variable(static_cast<uint32_t>(4294967294));
		ASSERT_EQ(result.Type, UINT64);
		ASSERT_EQ(result, 4294967304);
		result = Variable(static_cast<uint16_t>(10)) + Variable(static_cast<float>(10));
		ASSERT_EQ(result.Type, FLOAT);
		ASSERT_EQ(result, 20);
		result = Variable(static_cast<uint16_t>(10)) + Variable(static_cast<double>(10));
		ASSERT_EQ(result.Type, DOUBLE);
		ASSERT_EQ(result, 20);
		
		result = Variable(static_cast<uint32_t>(10)) + Variable(static_cast<uint8_t>(10));
		ASSERT_EQ(result.Type, UINT32);
		ASSERT_EQ(result, 20);
		result = Variable(static_cast<uint32_t>(10)) + Variable(static_cast<uint16_t>(10));
		ASSERT_EQ(result.Type, UINT32);
		ASSERT_EQ(result, 20);
		result = Variable(static_cast<uint32_t>(10)) + Variable(static_cast<uint32_t>(10));
		ASSERT_EQ(result.Type, UINT32);
		ASSERT_EQ(result, 20);
		result = Variable(static_cast<uint32_t>(10)) + Variable(static_cast<uint64_t>(10));
		ASSERT_EQ(result.Type, UINT32);
		ASSERT_EQ(result, 20);
		result = Variable(static_cast<uint32_t>(10)) + Variable(static_cast<int8_t>(10));
		ASSERT_EQ(result.Type, UINT32);
		ASSERT_EQ(result, 20);
		result = Variable(static_cast<uint32_t>(10)) + Variable(static_cast<int16_t>(10));
		ASSERT_EQ(result.Type, UINT32);
		ASSERT_EQ(result, 20);
		result = Variable(static_cast<uint32_t>(10)) + Variable(static_cast<int32_t>(10));
		ASSERT_EQ(result.Type, UINT32);
		ASSERT_EQ(result, 20);
		result = Variable(static_cast<uint32_t>(10)) + Variable(static_cast<int64_t>(10));
		ASSERT_EQ(result.Type, UINT32);
		ASSERT_EQ(result, 20);
		result = Variable(static_cast<uint32_t>(10)) + Variable(static_cast<int8_t>(-20));
		ASSERT_EQ(result.Type, INT32);
		ASSERT_EQ(result, -10);
		result = Variable(static_cast<uint32_t>(10)) + Variable(static_cast<int16_t>(-20));
		ASSERT_EQ(result.Type, INT32);
		ASSERT_EQ(result, -10);
		result = Variable(static_cast<uint32_t>(10)) + Variable(static_cast<int32_t>(-20));
		ASSERT_EQ(result.Type, INT32);
		ASSERT_EQ(result, -10);
		result = Variable(static_cast<uint32_t>(10)) + Variable(static_cast<int64_t>(-20));
		ASSERT_EQ(result.Type, INT32);
		ASSERT_EQ(result, -10);
		result = Variable(static_cast<uint32_t>(10)) + Variable(static_cast<int64_t>(-139));
		ASSERT_EQ(result.Type, INT32);
		ASSERT_EQ(result, -129);
		result = Variable(static_cast<uint32_t>(10)) + Variable(static_cast<int64_t>(-32779));
		ASSERT_EQ(result.Type, INT32);
		ASSERT_EQ(result, -32769);
		result = Variable(static_cast<uint32_t>(10)) + Variable(-static_cast<int64_t>(2147483659));
		ASSERT_EQ(result.Type, INT64);
		ASSERT_EQ(result, -static_cast<int64_t>(2147483649));
		result = Variable(static_cast<uint32_t>(10)) + Variable(static_cast<uint8_t>(250));
		ASSERT_EQ(result.Type, UINT32);
		ASSERT_EQ(result, 260);
		result = Variable(static_cast<uint32_t>(10)) + Variable(static_cast<uint16_t>(65534));
		ASSERT_EQ(result.Type, UINT32);
		ASSERT_EQ(result, 65544);
		result = Variable(static_cast<uint32_t>(10)) + Variable(static_cast<uint32_t>(4294967294));
		ASSERT_EQ(result.Type, UINT64);
		ASSERT_EQ(result, 4294967304);
		result = Variable(static_cast<uint32_t>(10)) + Variable(static_cast<float>(10));
		ASSERT_EQ(result.Type, FLOAT);
		ASSERT_EQ(result, 20);
		result = Variable(static_cast<uint32_t>(10)) + Variable(static_cast<double>(10));
		ASSERT_EQ(result.Type, DOUBLE);
		ASSERT_EQ(result, 20);
		
		result = Variable(static_cast<uint64_t>(10)) + Variable(static_cast<uint8_t>(10));
		ASSERT_EQ(result.Type, UINT64);
		ASSERT_EQ(result, 20);
		result = Variable(static_cast<uint64_t>(10)) + Variable(static_cast<uint16_t>(10));
		ASSERT_EQ(result.Type, UINT64);
		ASSERT_EQ(result, 20);
		result = Variable(static_cast<uint64_t>(10)) + Variable(static_cast<uint32_t>(10));
		ASSERT_EQ(result.Type, UINT64);
		ASSERT_EQ(result, 20);
		result = Variable(static_cast<uint64_t>(10)) + Variable(static_cast<uint64_t>(10));
		ASSERT_EQ(result.Type, UINT64);
		ASSERT_EQ(result, 20);
		result = Variable(static_cast<uint64_t>(10)) + Variable(static_cast<int8_t>(10));
		ASSERT_EQ(result.Type, UINT64);
		ASSERT_EQ(result, 20);
		result = Variable(static_cast<uint64_t>(10)) + Variable(static_cast<int16_t>(10));
		ASSERT_EQ(result.Type, UINT64);
		ASSERT_EQ(result, 20);
		result = Variable(static_cast<uint64_t>(10)) + Variable(static_cast<int32_t>(10));
		ASSERT_EQ(result.Type, UINT64);
		ASSERT_EQ(result, 20);
		result = Variable(static_cast<uint64_t>(10)) + Variable(static_cast<int64_t>(10));
		ASSERT_EQ(result.Type, UINT64);
		ASSERT_EQ(result, 20);
		result = Variable(static_cast<uint64_t>(10)) + Variable(static_cast<int8_t>(-20));
		ASSERT_EQ(result.Type, INT64);
		ASSERT_EQ(result, -10);
		result = Variable(static_cast<uint64_t>(10)) + Variable(static_cast<int16_t>(-20));
		ASSERT_EQ(result.Type, INT64);
		ASSERT_EQ(result, -10);
		result = Variable(static_cast<uint64_t>(10)) + Variable(static_cast<int32_t>(-20));
		ASSERT_EQ(result.Type, INT64);
		ASSERT_EQ(result, -10);
		result = Variable(static_cast<uint64_t>(10)) + Variable(static_cast<int64_t>(-20));
		ASSERT_EQ(result.Type, INT64);
		ASSERT_EQ(result, -10);
		result = Variable(static_cast<uint64_t>(10)) + Variable(static_cast<int64_t>(-139));
		ASSERT_EQ(result.Type, INT64);
		ASSERT_EQ(result, -129);
		result = Variable(static_cast<uint64_t>(10)) + Variable(static_cast<int64_t>(-32779));
		ASSERT_EQ(result.Type, INT64);
		ASSERT_EQ(result, -32769);
		result = Variable(static_cast<uint64_t>(10)) + Variable(-static_cast<int64_t>(2147483659));
		ASSERT_EQ(result.Type, INT64);
		ASSERT_EQ(result, -static_cast<int64_t>(2147483649));
		result = Variable(static_cast<uint64_t>(10)) + Variable(static_cast<uint8_t>(250));
		ASSERT_EQ(result.Type, UINT64);
		ASSERT_EQ(result, 260);
		result = Variable(static_cast<uint64_t>(10)) + Variable(static_cast<uint16_t>(65534));
		ASSERT_EQ(result.Type, UINT64);
		ASSERT_EQ(result, 65544);
		result = Variable(static_cast<uint64_t>(10)) + Variable(static_cast<uint32_t>(4294967294));
		ASSERT_EQ(result.Type, UINT64);
		ASSERT_EQ(result, 4294967304);
		result = Variable(static_cast<uint64_t>(10)) + Variable(static_cast<float>(10));
		ASSERT_EQ(result.Type, FLOAT);
		ASSERT_EQ(result, 20);
		result = Variable(static_cast<uint64_t>(10)) + Variable(static_cast<double>(10));
		ASSERT_EQ(result.Type, DOUBLE);
		ASSERT_EQ(result, 20);
		
		result = Variable(static_cast<int8_t>(10)) + Variable(static_cast<uint8_t>(10));
		ASSERT_EQ(result.Type, INT8);
		ASSERT_EQ(result, 20);
		result = Variable(static_cast<int8_t>(10)) + Variable(static_cast<uint16_t>(10));
		ASSERT_EQ(result.Type, INT8);
		ASSERT_EQ(result, 20);
		result = Variable(static_cast<int8_t>(10)) + Variable(static_cast<uint32_t>(10));
		ASSERT_EQ(result.Type, INT8);
		ASSERT_EQ(result, 20);
		result = Variable(static_cast<int8_t>(10)) + Variable(static_cast<uint64_t>(10));
		ASSERT_EQ(result.Type, INT8);
		ASSERT_EQ(result, 20);
		result = Variable(static_cast<int8_t>(10)) + Variable(static_cast<int8_t>(10));
		ASSERT_EQ(result.Type, INT8);
		ASSERT_EQ(result, 20);
		result = Variable(static_cast<int8_t>(10)) + Variable(static_cast<int16_t>(10));
		ASSERT_EQ(result.Type, INT8);
		ASSERT_EQ(result, 20);
		result = Variable(static_cast<int8_t>(10)) + Variable(static_cast<int32_t>(10));
		ASSERT_EQ(result.Type, INT8);
		ASSERT_EQ(result, 20);
		result = Variable(static_cast<int8_t>(10)) + Variable(static_cast<int64_t>(10));
		ASSERT_EQ(result.Type, INT8);
		ASSERT_EQ(result, 20);
		result = Variable(static_cast<int8_t>(10)) + Variable(static_cast<int8_t>(-20));
		ASSERT_EQ(result.Type, INT8);
		ASSERT_EQ(result, -10);
		result = Variable(static_cast<int8_t>(10)) + Variable(static_cast<int16_t>(-20));
		ASSERT_EQ(result.Type, INT8);
		ASSERT_EQ(result, -10);
		result = Variable(static_cast<int8_t>(10)) + Variable(static_cast<int32_t>(-20));
		ASSERT_EQ(result.Type, INT8);
		ASSERT_EQ(result, -10);
		result = Variable(static_cast<int8_t>(10)) + Variable(static_cast<int64_t>(-20));
		ASSERT_EQ(result.Type, INT8);
		ASSERT_EQ(result, -10);
		result = Variable(static_cast<int8_t>(10)) + Variable(static_cast<int64_t>(-139));
		ASSERT_EQ(result.Type, INT16);
		ASSERT_EQ(result, -129);
		result = Variable(static_cast<int8_t>(10)) + Variable(static_cast<int64_t>(-32779));
		ASSERT_EQ(result.Type, INT32);
		ASSERT_EQ(result, -32769);
		result = Variable(static_cast<int8_t>(10)) + Variable(-static_cast<int64_t>(2147483659));
		ASSERT_EQ(result.Type, INT64);
		ASSERT_EQ(result, -static_cast<int64_t>(2147483649));
		result = Variable(static_cast<int8_t>(10)) + Variable(static_cast<uint8_t>(128));
		ASSERT_EQ(result.Type, INT16);
		ASSERT_EQ(result, 138);
		result = Variable(static_cast<int8_t>(10)) + Variable(static_cast<uint16_t>(32768));
		ASSERT_EQ(result.Type, INT32);
		ASSERT_EQ(result, 32778);
		result = Variable(static_cast<int8_t>(10)) + Variable(static_cast<uint32_t>(2147483648));
		ASSERT_EQ(result.Type, INT64);
		ASSERT_EQ(result, 2147483658);
		result = Variable(static_cast<int8_t>(10)) + Variable(static_cast<float>(10));
		ASSERT_EQ(result.Type, FLOAT);
		ASSERT_EQ(result, 20);
		result = Variable(static_cast<int8_t>(10)) + Variable(static_cast<double>(10));
		ASSERT_EQ(result.Type, DOUBLE);
		ASSERT_EQ(result, 20);
		
		result = Variable(static_cast<int16_t>(10)) + Variable(static_cast<uint8_t>(10));
		ASSERT_EQ(result.Type, INT16);
		ASSERT_EQ(result, 20);
		result = Variable(static_cast<int16_t>(10)) + Variable(static_cast<uint16_t>(10));
		ASSERT_EQ(result.Type, INT16);
		ASSERT_EQ(result, 20);
		result = Variable(static_cast<int16_t>(10)) + Variable(static_cast<uint32_t>(10));
		ASSERT_EQ(result.Type, INT16);
		ASSERT_EQ(result, 20);
		result = Variable(static_cast<int16_t>(10)) + Variable(static_cast<uint64_t>(10));
		ASSERT_EQ(result.Type, INT16);
		ASSERT_EQ(result, 20);
		result = Variable(static_cast<int16_t>(10)) + Variable(static_cast<int8_t>(10));
		ASSERT_EQ(result.Type, INT16);
		ASSERT_EQ(result, 20);
		result = Variable(static_cast<int16_t>(10)) + Variable(static_cast<int16_t>(10));
		ASSERT_EQ(result.Type, INT16);
		ASSERT_EQ(result, 20);
		result = Variable(static_cast<int16_t>(10)) + Variable(static_cast<int32_t>(10));
		ASSERT_EQ(result.Type, INT16);
		ASSERT_EQ(result, 20);
		result = Variable(static_cast<int16_t>(10)) + Variable(static_cast<int64_t>(10));
		ASSERT_EQ(result.Type, INT16);
		ASSERT_EQ(result, 20);
		result = Variable(static_cast<int16_t>(10)) + Variable(static_cast<int8_t>(-20));
		ASSERT_EQ(result.Type, INT16);
		ASSERT_EQ(result, -10);
		result = Variable(static_cast<int16_t>(10)) + Variable(static_cast<int16_t>(-20));
		ASSERT_EQ(result.Type, INT16);
		ASSERT_EQ(result, -10);
		result = Variable(static_cast<int16_t>(10)) + Variable(static_cast<int32_t>(-20));
		ASSERT_EQ(result.Type, INT16);
		ASSERT_EQ(result, -10);
		result = Variable(static_cast<int16_t>(10)) + Variable(static_cast<int64_t>(-20));
		ASSERT_EQ(result.Type, INT16);
		ASSERT_EQ(result, -10);
		result = Variable(static_cast<int16_t>(10)) + Variable(static_cast<int64_t>(-139));
		ASSERT_EQ(result.Type, INT16);
		ASSERT_EQ(result, -129);
		result = Variable(static_cast<int16_t>(10)) + Variable(static_cast<int64_t>(-32779));
		ASSERT_EQ(result.Type, INT32);
		ASSERT_EQ(result, -32769);
		result = Variable(static_cast<int16_t>(10)) + Variable(-static_cast<int64_t>(2147483659));
		ASSERT_EQ(result.Type, INT64);
		ASSERT_EQ(result, -static_cast<int64_t>(2147483649));
		result = Variable(static_cast<int16_t>(10)) + Variable(static_cast<uint8_t>(128));
		ASSERT_EQ(result.Type, INT16);
		ASSERT_EQ(result, 138);
		result = Variable(static_cast<int16_t>(10)) + Variable(static_cast<uint16_t>(32768));
		ASSERT_EQ(result.Type, INT32);
		ASSERT_EQ(result, 32778);
		result = Variable(static_cast<int16_t>(10)) + Variable(static_cast<uint32_t>(2147483648));
		ASSERT_EQ(result.Type, INT64);
		ASSERT_EQ(result, 2147483658);
		result = Variable(static_cast<int16_t>(10)) + Variable(static_cast<float>(10));
		ASSERT_EQ(result.Type, FLOAT);
		ASSERT_EQ(result, 20);
		result = Variable(static_cast<int16_t>(10)) + Variable(static_cast<double>(10));
		ASSERT_EQ(result.Type, DOUBLE);
		ASSERT_EQ(result, 20);
		
		result = Variable(static_cast<int32_t>(10)) + Variable(static_cast<uint8_t>(10));
		ASSERT_EQ(result.Type, INT32);
		ASSERT_EQ(result, 20);
		result = Variable(static_cast<int32_t>(10)) + Variable(static_cast<uint16_t>(10));
		ASSERT_EQ(result.Type, INT32);
		ASSERT_EQ(result, 20);
		result = Variable(static_cast<int32_t>(10)) + Variable(static_cast<uint32_t>(10));
		ASSERT_EQ(result.Type, INT32);
		ASSERT_EQ(result, 20);
		result = Variable(static_cast<int32_t>(10)) + Variable(static_cast<uint64_t>(10));
		ASSERT_EQ(result.Type, INT32);
		ASSERT_EQ(result, 20);
		result = Variable(static_cast<int32_t>(10)) + Variable(static_cast<int8_t>(10));
		ASSERT_EQ(result.Type, INT32);
		ASSERT_EQ(result, 20);
		result = Variable(static_cast<int32_t>(10)) + Variable(static_cast<int16_t>(10));
		ASSERT_EQ(result.Type, INT32);
		ASSERT_EQ(result, 20);
		result = Variable(static_cast<int32_t>(10)) + Variable(static_cast<int32_t>(10));
		ASSERT_EQ(result.Type, INT32);
		ASSERT_EQ(result, 20);
		result = Variable(static_cast<int32_t>(10)) + Variable(static_cast<int64_t>(10));
		ASSERT_EQ(result.Type, INT32);
		ASSERT_EQ(result, 20);
		result = Variable(static_cast<int32_t>(10)) + Variable(static_cast<int8_t>(-20));
		ASSERT_EQ(result.Type, INT32);
		ASSERT_EQ(result, -10);
		result = Variable(static_cast<int32_t>(10)) + Variable(static_cast<int16_t>(-20));
		ASSERT_EQ(result.Type, INT32);
		ASSERT_EQ(result, -10);
		result = Variable(static_cast<int32_t>(10)) + Variable(static_cast<int32_t>(-20));
		ASSERT_EQ(result.Type, INT32);
		ASSERT_EQ(result, -10);
		result = Variable(static_cast<int32_t>(10)) + Variable(static_cast<int64_t>(-20));
		ASSERT_EQ(result.Type, INT32);
		ASSERT_EQ(result, -10);
		result = Variable(static_cast<int32_t>(10)) + Variable(static_cast<int64_t>(-139));
		ASSERT_EQ(result.Type, INT32);
		ASSERT_EQ(result, -129);
		result = Variable(static_cast<int32_t>(10)) + Variable(static_cast<int64_t>(-32779));
		ASSERT_EQ(result.Type, INT32);
		ASSERT_EQ(result, -32769);
		result = Variable(static_cast<int32_t>(10)) + Variable(-static_cast<int64_t>(2147483659));
		ASSERT_EQ(result.Type, INT64);
		ASSERT_EQ(result, -static_cast<int64_t>(2147483649));
		result = Variable(static_cast<int32_t>(10)) + Variable(static_cast<uint8_t>(128));
		ASSERT_EQ(result.Type, INT32);
		ASSERT_EQ(result, 138);
		result = Variable(static_cast<int32_t>(10)) + Variable(static_cast<uint16_t>(32768));
		ASSERT_EQ(result.Type, INT32);
		ASSERT_EQ(result, 32778);
		result = Variable(static_cast<int32_t>(10)) + Variable(static_cast<uint32_t>(2147483648));
		ASSERT_EQ(result.Type, INT64);
		ASSERT_EQ(result, 2147483658);
		result = Variable(static_cast<int32_t>(10)) + Variable(static_cast<float>(10));
		ASSERT_EQ(result.Type, FLOAT);
		ASSERT_EQ(result, 20);
		result = Variable(static_cast<int32_t>(10)) + Variable(static_cast<double>(10));
		ASSERT_EQ(result.Type, DOUBLE);
		ASSERT_EQ(result, 20);
		
		result = Variable(static_cast<int64_t>(10)) + Variable(static_cast<uint8_t>(10));
		ASSERT_EQ(result.Type, INT64);
		ASSERT_EQ(result, 20);
		result = Variable(static_cast<int64_t>(10)) + Variable(static_cast<uint16_t>(10));
		ASSERT_EQ(result.Type, INT64);
		ASSERT_EQ(result, 20);
		result = Variable(static_cast<int64_t>(10)) + Variable(static_cast<uint32_t>(10));
		ASSERT_EQ(result.Type, INT64);
		ASSERT_EQ(result, 20);
		result = Variable(static_cast<int64_t>(10)) + Variable(static_cast<uint64_t>(10));
		ASSERT_EQ(result.Type, INT64);
		ASSERT_EQ(result, 20);
		result = Variable(static_cast<int64_t>(10)) + Variable(static_cast<int8_t>(10));
		ASSERT_EQ(result.Type, INT64);
		ASSERT_EQ(result, 20);
		result = Variable(static_cast<int64_t>(10)) + Variable(static_cast<int16_t>(10));
		ASSERT_EQ(result.Type, INT64);
		ASSERT_EQ(result, 20);
		result = Variable(static_cast<int64_t>(10)) + Variable(static_cast<int32_t>(10));
		ASSERT_EQ(result.Type, INT64);
		ASSERT_EQ(result, 20);
		result = Variable(static_cast<int64_t>(10)) + Variable(static_cast<int64_t>(10));
		ASSERT_EQ(result.Type, INT64);
		ASSERT_EQ(result, 20);
		result = Variable(static_cast<int64_t>(10)) + Variable(static_cast<int8_t>(-20));
		ASSERT_EQ(result.Type, INT64);
		ASSERT_EQ(result, -10);
		result = Variable(static_cast<int64_t>(10)) + Variable(static_cast<int16_t>(-20));
		ASSERT_EQ(result.Type, INT64);
		ASSERT_EQ(result, -10);
		result = Variable(static_cast<int64_t>(10)) + Variable(static_cast<int32_t>(-20));
		ASSERT_EQ(result.Type, INT64);
		ASSERT_EQ(result, -10);
		result = Variable(static_cast<int64_t>(10)) + Variable(static_cast<int64_t>(-20));
		ASSERT_EQ(result.Type, INT64);
		ASSERT_EQ(result, -10);
		result = Variable(static_cast<int64_t>(10)) + Variable(static_cast<int64_t>(-139));
		ASSERT_EQ(result.Type, INT64);
		ASSERT_EQ(result, -129);
		result = Variable(static_cast<int64_t>(10)) + Variable(static_cast<int64_t>(-32779));
		ASSERT_EQ(result.Type, INT64);
		ASSERT_EQ(result, -32769);
		result = Variable(static_cast<int64_t>(10)) + Variable(-static_cast<int64_t>(2147483659));
		ASSERT_EQ(result.Type, INT64);
		ASSERT_EQ(result, -static_cast<int64_t>(2147483649));
		result = Variable(static_cast<int64_t>(10)) + Variable(static_cast<uint8_t>(128));
		ASSERT_EQ(result.Type, INT64);
		ASSERT_EQ(result, 138);
		result = Variable(static_cast<int64_t>(10)) + Variable(static_cast<uint16_t>(32768));
		ASSERT_EQ(result.Type, INT64);
		ASSERT_EQ(result, 32778);
		result = Variable(static_cast<int64_t>(10)) + Variable(static_cast<uint32_t>(2147483648));
		ASSERT_EQ(result.Type, INT64);
		ASSERT_EQ(result, 2147483658);
		result = Variable(static_cast<int64_t>(10)) + Variable(static_cast<float>(10));
		ASSERT_EQ(result.Type, FLOAT);
		ASSERT_EQ(result, 20);
		result = Variable(static_cast<int64_t>(10)) + Variable(static_cast<double>(10));
		ASSERT_EQ(result.Type, DOUBLE);
		ASSERT_EQ(result, 20);
		
		result = Variable(static_cast<float>(10)) + Variable(static_cast<uint8_t>(10));
		ASSERT_EQ(result.Type, FLOAT);
		ASSERT_EQ(result, 20);
		result = Variable(static_cast<float>(10)) + Variable(static_cast<uint16_t>(10));
		ASSERT_EQ(result.Type, FLOAT);
		ASSERT_EQ(result, 20);
		result = Variable(static_cast<float>(10)) + Variable(static_cast<uint32_t>(10));
		ASSERT_EQ(result.Type, FLOAT);
		ASSERT_EQ(result, 20);
		result = Variable(static_cast<float>(10)) + Variable(static_cast<uint64_t>(10));
		ASSERT_EQ(result.Type, FLOAT);
		ASSERT_EQ(result, 20);
		result = Variable(static_cast<float>(10)) + Variable(static_cast<int8_t>(10));
		ASSERT_EQ(result.Type, FLOAT);
		ASSERT_EQ(result, 20);
		result = Variable(static_cast<float>(10)) + Variable(static_cast<int16_t>(10));
		ASSERT_EQ(result.Type, FLOAT);
		ASSERT_EQ(result, 20);
		result = Variable(static_cast<float>(10)) + Variable(static_cast<int32_t>(10));
		ASSERT_EQ(result.Type, FLOAT);
		ASSERT_EQ(result, 20);
		result = Variable(static_cast<float>(10)) + Variable(static_cast<int64_t>(10));
		ASSERT_EQ(result.Type, FLOAT);
		ASSERT_EQ(result, 20);
		result = Variable(static_cast<float>(10)) + Variable(static_cast<float>(10));
		ASSERT_EQ(result.Type, FLOAT);
		ASSERT_EQ(result, 20);
		result = Variable(static_cast<float>(10)) + Variable(static_cast<double>(10));
		ASSERT_EQ(result.Type, DOUBLE);
		ASSERT_EQ(result, 20);
		
		result = Variable(static_cast<double>(10)) + Variable(static_cast<uint8_t>(10));
		ASSERT_EQ(result.Type, DOUBLE);
		ASSERT_EQ(result, 20);
		result = Variable(static_cast<double>(10)) + Variable(static_cast<uint16_t>(10));
		ASSERT_EQ(result.Type, DOUBLE);
		ASSERT_EQ(result, 20);
		result = Variable(static_cast<double>(10)) + Variable(static_cast<uint32_t>(10));
		ASSERT_EQ(result.Type, DOUBLE);
		ASSERT_EQ(result, 20);
		result = Variable(static_cast<double>(10)) + Variable(static_cast<uint64_t>(10));
		ASSERT_EQ(result.Type, DOUBLE);
		ASSERT_EQ(result, 20);
		result = Variable(static_cast<double>(10)) + Variable(static_cast<int8_t>(10));
		ASSERT_EQ(result.Type, DOUBLE);
		ASSERT_EQ(result, 20);
		result = Variable(static_cast<double>(10)) + Variable(static_cast<int16_t>(10));
		ASSERT_EQ(result.Type, DOUBLE);
		ASSERT_EQ(result, 20);
		result = Variable(static_cast<double>(10)) + Variable(static_cast<int32_t>(10));
		ASSERT_EQ(result.Type, DOUBLE);
		ASSERT_EQ(result, 20);
		result = Variable(static_cast<double>(10)) + Variable(static_cast<int64_t>(10));
		ASSERT_EQ(result.Type, DOUBLE);
		ASSERT_EQ(result, 20);
		result = Variable(static_cast<double>(10)) + Variable(static_cast<float>(10));
		ASSERT_EQ(result.Type, DOUBLE);
		ASSERT_EQ(result, 20);
		result = Variable(static_cast<float>(10)) + Variable(static_cast<double>(10));
		ASSERT_EQ(result.Type, DOUBLE);
		ASSERT_EQ(result, 20);
	}

	TEST(VariableTests, WhenSubtacting_ThenCorrectValueReturned)
	{
		Variable result;
		
		result = Variable(static_cast<uint8_t>(10)) - Variable(static_cast<uint8_t>(5));
		ASSERT_EQ(result.Type, UINT8);
		ASSERT_EQ(result, 5);

		result = Variable(static_cast<uint8_t>(10)) - Variable(static_cast<uint8_t>(15));
		ASSERT_EQ(result.Type, INT8);
		ASSERT_EQ(result, -5);
	}

	TEST(VariableTests, WhenMultiplying_ThenCorrectValueReturned)
	{
		Variable result;
		
		result = Variable(static_cast<uint8_t>(10)) * Variable(static_cast<uint8_t>(5));
		ASSERT_EQ(result.Type, UINT8);
		ASSERT_EQ(result, 50);

		result = Variable(static_cast<uint8_t>(10)) * Variable(static_cast<int8_t>(-15));
		ASSERT_EQ(result.Type, INT16);
		ASSERT_EQ(result, -150);
	}

	TEST(VariableTests, WhenDividing_ThenCorrectValueReturned)
	{
		Variable result;
		
		result = Variable(static_cast<uint8_t>(10)) / Variable(static_cast<uint8_t>(5));
		ASSERT_EQ(result.Type, UINT8);
		ASSERT_EQ(result, 2);

		result = Variable(static_cast<uint16_t>(150)) / Variable(static_cast<int8_t>(-15));
		ASSERT_EQ(result.Type, INT16);
		ASSERT_EQ(result, -10);
	}

	TEST(VariableTests, WhenImplicitConversion_ThenCorrectValueReturned)
	{
		Variable test = static_cast<uint8_t>(10);
		uint8_t uint8test = test;
		ASSERT_EQ(uint8test, 10);

		test = static_cast<double>(10.5);
		double doubletest = test;
		ASSERT_FLOAT_EQ(doubletest, 10.5);
		uint8test = test;
		ASSERT_EQ(uint8test, 10);
	}
}
